### ISSUE TITLE
Crash - Exception: kotlin.UninitializedPropertyAccessException: lateinit property login has not been initialized

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#529]
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (F-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : Core-X4 NEO (2022022410 11 REL)
Memory statuses
usedSize 13 MB
freeSize 15 MB
totalSize 29 MB
Thread: main, Exception: kotlin.UninitializedPropertyAccessException: lateinit property login has not been initialized
at fr.gouv.tchap.features.login.TchapLoginFragment$onViewCreated$1.invoke(TchapLoginFragment.kt:8)
at fr.gouv.tchap.features.login.TchapLoginFragment$onViewCreated$1.invoke(TchapLoginFragment.kt:1)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invokeSuspend(VectorBaseFragment.kt:3)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invoke(Unknown Source:8)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:6)
at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:12)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:10)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:14)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:6)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:4)
at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:6)
at im.vector.app.features.login.LoginViewModel$getLoginFlow$1.invokeSuspend(LoginViewModel.kt:35)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7705)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:605)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID 65d6cc14dbf93d8; Flavour FDroid; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (F-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "develop11"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
device_id: "BLWQJKZIXP"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) 2022022410-REL"
server_version: "undefined"
theme: "system"

**Comment by Claire1817** [comment]
Copy of: https://github.com/tchapgouv/tchap-android/issues/557
