### ISSUE TITLE
Crash - Scroll vers le bas dans une conversation Exception: java.lang.IllegalArgumentException: Given text can not be applied to TextView.

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#532]
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : SM-G930F (G930FXXU8ETI2 8.0.0 REL)
Memory statuses
usedSize 15 MB
freeSize 14 MB
totalSize 30 MB
Thread: main, Exception: java.lang.IllegalArgumentException: Given text can not be applied to TextView.
at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:9)
at androidx.appcompat.widget.AppCompatTextView.consumeTextFutureAndSetBlocking(AppCompatTextView.java:3)
at androidx.appcompat.widget.AppCompatTextView.getText(AppCompatTextView.java:1)
at androidx.emoji2.viewsintegration.EmojiInputFilter.filter(EmojiInputFilter.java:4)
at android.widget.TextView.setText(TextView.java:5900)
at android.widget.TextView.setText(TextView.java:5865)
at android.widget.TextView.setText(TextView.java:5822)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:44)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:6)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:25)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:3)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:131)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:13)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 8.0.0; SM-G930F Build/R16N; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G930F"
device_id: "WQPMBWBSGF"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "8.0.0 (API 26) G930FXXU8ETI2-REL"
server_version: "undefined"
theme: "light"

**Comment by appndigital** [comment]
Duplicate with #531
