### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android#537]
### Steps to reproduce

 crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : ONEPLUS A6003
Memory statuses
usedSize 12 MB
freeSize 8 MB
totalSize 20 MB
Thread: main, Exception: NetworkConnection(ioException=java.net.SocketTimeoutException: failed to connect to matrix.agent.ssi.tchap.gouv.fr/2a0d:e487:ffff::8fc4:fd65 (port 443) from /2a01:e34:ed32:fdb0:c8d8:1907:5fb3:1236 (port 42722) after 30000ms)
at org.matrix.android.sdk.internal.session.openid.DefaultGetOpenIdTokenTask.execute(GetOpenIdTokenTask.kt:32)
at org.matrix.android.sdk.internal.session.openid.DefaultGetOpenIdTokenTask$execute$1.invokeSuspend(Unknown Source:11)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:233)
at android.app.ActivityThread.main(ActivityThread.java:8068)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:631)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.net.SocketTimeoutException: failed to connect to matrix.agent.ssi.tchap.gouv.fr/2a0d:e487:ffff::8fc4:fd65 (port 443) from /2a01:e34:ed32:fdb0:c8d8:1907:5fb3:1236 (port 42722) after 30000ms
at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
at libcore.io.IoBridge.connect(IoBridge.java:134)
at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
at java.net.Socket.connect(Socket.java:621)
at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:1)
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection..kt:18)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:26)
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:111)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:20)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:30)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:37)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:36)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at org.matrix.android.sdk.internal.network.AccessTokenInterceptor.intercept(AccessTokenInterceptor.kt:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at org.matrix.android.sdk.internal.network.ApiInterceptor.intercept(ApiInterceptor.kt:8)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor..kt:57)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at org.matrix.android.sdk.internal.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:29)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at org.matrix.android.sdk.internal.network.TimeOutInterceptor.intercept(TimeOutInterceptor.kt:33)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:23)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:12)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; ONEPLUS A6003 Build/RKQ1.201217.00; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "ONEPLUS A6003"
device_id: "WCVALRPPAH"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30)"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

![image](https://user-images.githubusercontent.com/73166724/162211737-9974199f-b63f-431c-b58a-7cda647856fb.png)

#### What did you expect?
No crash

### Your phone model

ONEPLUS A6003

### Operating system version

Android 2.0.3

### Application version and app store

olm version (3.2.7)

### Will you send logs?

Yes

**Comment by Claire1817** [comment]
Same issue: https://github.com/tchapgouv/tchap-android-v2/issues/504
