### ISSUE TITLE
Crash: open private room by link

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android#554]
- Create room -> settings -> room settings
- Enable Access by link
- Send link in another room
- With another account open the link and clic on "open"
- Crash

Stacktrace:
```
2022-04-14 11:15:22.828 28473-28473/fr.gouv.tchap.a E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.gouv.tchap.a, PID: 28473
    java.lang.IllegalStateException: Trying to open an unknown room #testprivezhMfP0RkCF:agent.social.tchap.gouv.fr
        at im.vector.app.core.error.FatalKt.fatalError(fatal.kt:26)
        at im.vector.app.features.navigation.DefaultNavigator.openRoom(DefaultNavigator.kt:144)
        at im.vector.app.features.navigation.Navigator$DefaultImpls.openRoom$default(Navigator.kt:49)
        at im.vector.app.features.home.room.detail.RoomDetailActivity.mxToBottomSheetNavigateToRoom(RoomDetailActivity.kt:209)
        at im.vector.app.features.matrixto.MatrixToBottomSheet$onViewCreated$1.invoke(MatrixToBottomSheet.kt:101)
        at im.vector.app.features.matrixto.MatrixToBottomSheet$onViewCreated$1.invoke(MatrixToBottomSheet.kt:98)
        at im.vector.app.core.platform.VectorBaseBottomSheetDialogFragment$observeViewEvents$1.invokeSuspend(VectorBaseBottomSheetDialogFragment.kt:188)
        at im.vector.app.core.platform.VectorBaseBottomSheetDialogFragment$observeViewEvents$1.invoke(Unknown Source:8)
        at im.vector.app.core.platform.VectorBaseBottomSheetDialogFragment$observeViewEvents$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:136)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:368)
        at im.vector.app.core.utils.PublishDataSource.post(DataSource.kt:62)
        at im.vector.app.features.matrixto.MatrixToBottomSheetViewModel$handleJoinRoom$2.invokeSuspend(MatrixToBottomSheetViewModel.kt:300)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2022-04-14 11:15:22.879 513-8082/? E/FrameEvents: updateAcquireFence: Did not find frame.
2022-04-14 11:15:24.208 29152-29152/fr.gouv.tchap.a E/ConstraintLayout: layout_constraintHeight_default="wrap" is deprecated.
    Use layout_height="WRAP_CONTENT" and layout_constrainedHeight="true" instead.
2022-04-14 11:15:24.440 29152-29195/fr.gouv.tchap.a E/DefaultGetKeysBackupLastVersionTask: Exception when executing request GET https://matrix.agent.dinum.tchap.gouv.fr/_matrix/client/unstable/room_keys/version
2022-04-14 11:15:24.598 29152-29152/fr.gouv.tchap.a E/TaskExecutor$execute: Task failed
    ServerError(error=MatrixError(code=M_NOT_FOUND, message=No backup found, consentUri=null, limitType=null, adminUri=null, retryAfterMillis=null, isSoftLogout=null, newLookupPepper=null, session=null, completedStages=null, flows=null, params=null), httpCode=404)
        at org.matrix.android.sdk.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:103)
        at org.matrix.android.sdk.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:66)
        at org.matrix.android.sdk.internal.crypto.keysbackup.tasks.DefaultGetKeysBackupLastVersionTask.execute(GetKeysBackupLastVersionTask.kt:54)
        at org.matrix.android.sdk.internal.crypto.keysbackup.tasks.DefaultGetKeysBackupLastVersionTask$execute$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Claire1817** [comment]
PR merged in Element: https://github.com/vector-im/element-android/pull/5786

**Comment by giomfo** [comment]
blocked until the next rebase against Element-Android

**Comment by giomfo** [comment]
need Element-android > v1.4.12

**Comment by Claire1817** [comment]
Tests : OK :)
