### ISSUE TITLE
Crash -  Exception: java.lang.IllegalStateException: Trying to open an unknown room #testTcx64j95ct:agent.social.tchap.gouv.fr

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#555]
crash call stack ---------------------------------
Element Build : 40202002
Element Version : 2.2.0-dev [40202002] (G-d3e897fa-2022-04-12 16:04:01 +0200)
SDK Version : 1.4.8 (d3e897fa)
Phone : SM-G950U (G950USQS7DSL2 9 REL)
Memory statuses
usedSize 28 MB
freeSize 7 MB
totalSize 35 MB
Thread: main, Exception: java.lang.IllegalStateException: Trying to open an unknown room [#testTcx64j95ct:agent.social.tchap.gouv.fr](http:/#testTcx64j95ct:agent.social.tchap.gouv.fr/)
at im.vector.app.core.error.FatalKt.fatalError(fatal.kt:26)
at im.vector.app.features.navigation.DefaultNavigator.openRoom(DefaultNavigator.kt:157)
at im.vector.app.features.navigation.Navigator$DefaultImpls.openRoom$default(Navigator.kt:53)
at im.vector.app.features.home.room.detail.RoomDetailActivity.mxToBottomSheetNavigateToRoom(RoomDetailActivity.kt:209)
at im.vector.app.features.matrixto.MatrixToBottomSheet$onViewCreated$1.invoke(MatrixToBottomSheet.kt:101)
at im.vector.app.features.matrixto.MatrixToBottomSheet$onViewCreated$1.invoke(MatrixToBottomSheet.kt:98)
at im.vector.app.core.platform.VectorBaseBottomSheetDialogFragment$observeViewEvents$1.invokeSuspend(VectorBaseBottomSheetDialogFragment.kt:197)
at im.vector.app.core.platform.VectorBaseBottomSheetDialogFragment$observeViewEvents$1.invoke(Unknown Source:8)
at im.vector.app.core.platform.VectorBaseBottomSheetDialogFragment$observeViewEvents$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:136)
at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:368)
at im.vector.app.core.utils.PublishDataSource.post(DataSource.kt:62)
at im.vector.app.features.matrixto.MatrixToBottomSheetViewModel$handleJoinRoom$2.invokeSuspend(MatrixToBottomSheetViewModel.kt:300)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7073)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

User-Agent: "Tchap/2.2.0-dev (Linux; U; Android 9; SM-G950U Build/PPR1.180610.01; Flavour GooglePlay; MatrixAndroidSdk2 1.4.8)"
Version: "2.2.0-dev [40202002] (G-d3e897fa-2022-04-12 16:04:01 +0200)"
app_language: "fr_FR"
branch_name: "cgizard/ISSUE-548"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G950U"
device_id: "NDHTPNIKCH"
locale: "fr_FR"
matrix_sdk_version: "1.4.8 (d3e897fa)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "9 (API 28) G950USQS7DSL2-REL"
server_version: "undefined"
theme: "system"

**Comment by Claire1817** [comment]
ISSUE - merged on element: Thank's for the logs.
https://github.com/vector-im/element-android/pull/5786
