### ISSUE TITLE
Crash - Exception: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android#556]
### Steps to reproduce

crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (F-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : Core-X4 NEO (2022031712 11 REL)
Memory statuses
usedSize 28 MB
freeSize 0 MB
totalSize 29 MB
Thread: TIMELINE_DB_THREAD, Exception: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
at io.realm.BaseRealm.checkIfValid(BaseRealm.java:4)
at io.realm.RealmResults.isLoaded(RealmResults.java:1)
at io.realm.OrderedRealmCollectionImpl.size(OrderedRealmCollectionImpl.java:1)
at java.util.AbstractCollection.isEmpty(AbstractCollection.java:86)
at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:7)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline.getLiveChunk(DefaultTimeline.kt:1)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline.executePaginationTask(DefaultTimeline.kt:1)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline$$ExternalSyntheticLambda4.run(Unknown Source:3)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID 30a0cd8a7c96e3c2; Flavour FDroid; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (F-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "develop11"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) 2022031712-REL"
server_version: "undefined"
theme: "system"
verbose_log: "OFF"

![image](https://user-images.githubusercontent.com/73166724/163540396-41b90041-64c0-4ac6-ac76-ca5052bd512c.png)

### Your phone model

Core-X4 NEO 

### Operating system version

Android 2.0.3 

### Application version and app store

olm_version: "3.2.7 - olm version (3.2.7) 

### Will you send logs?

No

**Comment by Nivann** [comment]
Crash suite à une demande de partage de clef depuis un autre terminal

**Comment by Claire1817** [comment]
Crash related to: https://github.com/vector-im/element-android/issues/3610
