### ISSUE TITLE
Crash - Exception: java.lang.RuntimeException: Canvas: trying to draw too large(108576768bytes) bitmap.

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#570]
Crash when user try to download a pic from a conversation on Tchap

crash call stack ---------------------------------
Tchap Build : 90
Tchap Version : 1.2.3_a (G-2a2c63d33-2021-11-19 19:52:27 +0100)
SDK Version : 0.9.37-dev (68165b6d-2020-12-09 16:15:52 +0100)
Phone : SM-G991B (G991BXXU4BULF 12 REL)
Memory statuses
usedSize 42 MB
freeSize 23 MB
totalSize 65 MB
Thread: main, Activity:im.vector.activity.VectorRoomActivity, Exception: java.lang.RuntimeException: Canvas: trying to draw too large(108576768bytes) bitmap.
at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:97)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:560)
at android.widget.ImageView.onDraw(ImageView.java:1462)
at android.view.View.draw(View.java:23893)
at android.view.View.updateDisplayListIfDirty(View.java:22762)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.draw(View.java:23896)
at android.view.View.updateDisplayListIfDirty(View.java:22762)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.draw(View.java:23896)
at android.view.View.updateDisplayListIfDirty(View.java:22762)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.widget.ListView.drawChild(ListView.java:3832)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.widget.AbsListView.dispatchDraw(AbsListView.java:2933)
at android.widget.ListView.dispatchDraw(ListView.java:3811)
at android.view.View.draw(View.java:23896)
at android.widget.AbsListView.draw(AbsListView.java:5034)
at android.view.View.updateDisplayListIfDirty(View.java:22762)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.draw(View.java:23896)
at com.android.internal.policy.DecorView.draw(DecorView.java:1348)
at android.view.View.updateDisplayListIfDirty(View.java:22762)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:5290)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4998)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4094)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2819)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10304)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
at android.view.Choreographer.doCallbacks(Choreographer.java:845)
at android.view.Choreographer.doFrame(Choreographer.java:780)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8582)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:563)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

User-Agent: "Tchap/1.2.3_a (Linux; U; Android 12; SM-G991B Build/SP1A.210812.01; Flavour appAgentWithoutvoipWithpinning; MatrixAndroidSDK 0.9.37-dev)"
Version: "1.2.3_a (G-2a2c63d33-2021-11-19 19:52:27 +0100)"
app_language: "fr_FR"
branch_name: "tags/tchap_v1.2.3^0"
default_app_language: "fr_FR"
device: "SM-G991B"
device_id: "MIBQDZZVYX"
lazy_loading: "ON"
locale: "fr_FR"
matrix_sdk_version: "0.9.37-dev (68165b6d-2020-12-09 16:15:52 +0100)"
multi_window: "OFF"
olm_version: "3.1.2 - olm version (3.1.2) - a18a4e8-2019-05-20 21:39:54 +0100"
os: "12 (API 31) G991BXXU4BULF-REL"
theme: "light"

**Comment by Nivann** [comment]
+1 : 

crash call stack ---------------------------------
Element Build : 40203012
Element Version : 2.3.1 [40203012] (G-bee4dc7d-2022-05-25 14:29:50 +0200)
SDK Version : 1.4.11 (bee4dc7d)
Phone : M2101K7AG 
Memory statuses
usedSize 43 MB
freeSize 23 MB
totalSize 67 MB
Thread: main, Exception: java.lang.RuntimeException: Canvas: trying to draw too large(120422400bytes) bitmap.
at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
at android.widget.ImageView.onDraw(ImageView.java:1480)
at android.view.View.draw(View.java:23005)
at android.view.View.updateDisplayListIfDirty(View.java:21873)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.updateDisplayListIfDirty(View.java:21864)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:1)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.updateDisplayListIfDirty(View.java:21864)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.draw(View.java:23009)
at android.view.View.updateDisplayListIfDirty(View.java:21873)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.updateDisplayListIfDirty(View.java:21864)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.updateDisplayListIfDirty(View.java:21864)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.updateDisplayListIfDirty(View.java:21864)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.updateDisplayListIfDirty(View.java:21864)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.updateDisplayListIfDirty(View.java:21864)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.updateDisplayListIfDirty(View.java:21864)
at android.view.View.draw(View.java:22731)
at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
at android.view.View.draw(View.java:23009)
at com.android.internal.policy.DecorView.draw(DecorView.java:887)
at android.view.View.updateDisplayListIfDirty(View.java:21873)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4643)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4361)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3472)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2263)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8990)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1144)
at android.view.Choreographer.doCallbacks(Choreographer.java:948)
at android.view.Choreographer.doFrame(Choreographer.java:877)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1129)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8291)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

User-Agent: "Tchap/2.3.1 (Linux; U; Android 12; M2101K7AG Build/SKQ1.210908..00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.1 [40203012] (G-bee4dc7d-2022-05-25 14:29:50 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "M2101K7AG"
device_id: "HZYFYBHGUF"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (bee4dc7d)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "12 (API 31) 
server_version: "undefined"
theme: "light"

**Comment by Nivann** [comment]
+1

**Comment by Nivann** [comment]
+ 2

**Comment by jdauphant** [comment]
Fixed in 2.4.2
