### ISSUE TITLE
Crash - Exception: java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#572]
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : SM-G960F (G960FXXUHFVB4 10 REL)
Memory statuses
usedSize 14 MB
freeSize 7 MB
totalSize 21 MB
Thread: main, Exception: java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using setTextMetricsParams(precomputedText.getParams()) to override the settings of this TextView: PrecomputedText: {textSize=54.6, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR], typeface=android.graphics.Typeface@b3409e55, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@9261b3b, breakStrategy=1, hyphenationFrequency=0}TextView: {textSize=171.59999, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR], typeface=android.graphics.Typeface@b3409e55, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@9261b3b, breakStrategy=1, hyphenationFrequency=0}
at android.widget.TextView.setText(TextView.java:6720)
at android.widget.TextView.setText(TextView.java:6638)
at android.widget.TextView.setText(TextView.java:6590)
at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:4)
at androidx.appcompat.widget.AppCompatTextView.consumeTextFutureAndSetBlocking(AppCompatTextView.java:3)
at androidx.appcompat.widget.AppCompatTextView.getText(AppCompatTextView.java:1)
at androidx.emoji2.viewsintegration.EmojiInputFilter.filter(EmojiInputFilter.java:4)
at android.widget.TextView.setText(TextView.java:6674)
at android.widget.TextView.setText(TextView.java:6638)
at android.widget.TextView.setText(TextView.java:6590)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:44)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:6)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:25)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:3)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:131)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:13)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 10; SM-G960F Build/QP1A.190711.02; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G960F"
device_id: "WAWSOFSCJX"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "10 (API 29) G960FXXUHFVB4-REL"
server_version: "undefined"
theme: "light"

**Comment by Claire1817** [comment]
This issue looks related to: https://github.com/vector-im/element-android/issues/4789
Fix in Element v1.4.13, this version is present in Tchap v2.2.0. 
This stacktrace comes from Tchap v2.0.3.
I close the issue and we will create a new one if the crash happens again.
