### ISSUE TITLE
 crash call stack -  the application stops for no reason - Exception: java.lang.IllegalArgumentException: PrecomputedText's 

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android#577]
### Steps to reproduce

crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : SM-A505FN
Memory statuses
usedSize 16 MB
freeSize 13 MB
totalSize 30 MB
Thread: main, Exception: java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using setTextMetricsParams(precomputedText.getParams()) to override the settings of this TextView: PrecomputedText: {textSize=36.75, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR], typeface=android.graphics.Typeface@595b86bc, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@43c77cb, breakStrategy=1, hyphenationFrequency=0}TextView: {textSize=115.5, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR], typeface=android.graphics.Typeface@595b86bc, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@43c77cb, breakStrategy=1, hyphenationFrequency=0}
at android.widget.TextView.setText(TextView.java:6844)
at android.widget.TextView.setText(TextView.java:6761)
at android.widget.TextView.setText(TextView.java:6713)
at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:4)
at androidx.appcompat.widget.AppCompatTextView.consumeTextFutureAndSetBlocking(AppCompatTextView.java:3)
at androidx.appcompat.widget.AppCompatTextView.getText(AppCompatTextView.java:1)
at androidx.emoji2.viewsintegration.EmojiInputFilter.filter(EmojiInputFilter.java:4)
at android.widget.TextView.setText(TextView.java:6797)
at android.widget.TextView.setText(TextView.java:6761)
at android.widget.TextView.setText(TextView.java:6713)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:44)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:6)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:25)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:3)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:131)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:13)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8633)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; SM-A505FN Build/RP1A.200720..01; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-A505FN"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30)"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

### Your phone model

SM-A505FN

### Operating system version

Android 11

### Application version and app store

Android 2.0.3

### Will you send logs?

No

**Comment by Claire1817** [comment]
Same crash here : https://github.com/tchapgouv/tchap-android/issues/572
