### ISSUE TITLE
Crash - Exception: java.lang.RuntimeException: Unable to create application im.vector.app.

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#583]
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : SM-G930F (G930FXXU8ETI2 8.0.0 REL)
Memory statuses
usedSize 8 MB
freeSize 4 MB
totalSize 13 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: java.lang.RuntimeException: /data/user/0/fr.gouv.tchap.a/files/e21f933c82268e15172819dab365bc2a/disk_store.realm: Encrypted interprocess sharing is currently unsupported.DB has been opened by pid: 16162. Current pid is 16337. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6065)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.RuntimeException: /data/user/0/fr.gouv.tchap.a/files/e21f933c82268e15172819dab365bc2a/disk_store.realm: Encrypted interprocess sharing is currently unsupported.DB has been opened by pid: 16162. Current pid is 16337. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:11)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
at io.realm.BaseRealm.<init>(BaseRealm.java:26)
at io.realm.Realm.<init>(Realm.java:8)
at io.realm.RealmCache.createInstance(RealmCache.java:2)
at io.realm.Realm.getInstance(Realm.java:21)
at org.matrix.android.sdk.internal.worker.MatrixWorkerFactory_Factory.get(MatrixWorkerFactory_Factory.java:40)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:1)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
at org.matrix.android.sdk.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:1)
at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:3)
at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:67)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
... 8 more

User-Agent: "Tchap/2.0.3 (Linux; U; Android 8.0.0; SM-G930F Build/R16N; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G930F"
device_id: "UGKWWKESNW"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "8.0.0 (API 26) G930FXXU8ETI2-REL"
server_version: "undefined"
theme: "light"

**Comment by Nivann** [comment]
+1

**Comment by Nivann** [comment]
+1 crash call stack ---------------------------------
Element Build : 40203012
Element Version : 2.3.1 [40203012] (G-bee4dc7d-2022-05-25 14:29:50 +0200)
SDK Version : 1.4.11 (bee4dc7d)
Phone : SM-A525F
Memory statuses
usedSize 13 MB
freeSize 242 MB
totalSize 256 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: java.lang.RuntimeException: /data/user/0/fr.gouv.tchap.a/files/9005799fddcbdc1c83f785ad198d05f9/disk_store.realm: Encrypted interprocess sharing is currently unsupported.DB has been opened by pid: 6819. Current pid is 19262. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7511)
at android.app.ActivityThread.access$1600(ActivityThread.java:310)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.RuntimeException: /data/user/0/fr.gouv.tchap.a/files/9005799fddcbdc1c83f785ad198d05f9/disk_store.realm: Encrypted interprocess sharing is currently unsupported.DB has been opened by pid: 6819. Current pid is 19262. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:11)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
at io.realm.BaseRealm.<init>(BaseRealm.java:26)
at io.realm.Realm.<init>(Realm.java:8)
at io.realm.RealmCache.createInstance(RealmCache.java:2)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:16)
at io.realm.Realm.getInstance(Realm.java:4)
at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:38)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:1)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
at org.matrix.android.sdk.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:1)
at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:3)
at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:94)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
... 9 more

User-Agent: "Tchap/2.3.1 (Linux; U; Android 12; SM-A525F Build/SP1A.210812.01; Flavour GooglePlay; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.1 [40203012] (G-bee4dc7d-2022-05-25 14:29:50 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "true"
default_app_language: "fr_FR"
device: "SM-A525F"
device_id: "OAAVIGBPRX"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (bee4dc7d)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "12 (API 31) 
server_version: "undefined"
theme: "light"

**Comment by Nivann** [comment]
+1

**Comment by estellecomment** [comment]
+1 https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_775da970-e62a-4b7b-ba55-305f96599b6d/
User says it happens every two months approximately, when there are many apps open and the phone has not been used recently. When she goes back to the Tchap app, the screen stays black. She solves it by force-closing the app and restarting it.

**Comment by Nivann** [comment]
+1 sur la 2.4.4 également

**Comment by AmelAlili** [comment]
+1 
tchap-android] [tchap] arrêt inopinée

User message:

[tchap] arrêt inopinée
 crash call stack ---------------------------------
Element Build : 402040402
Element Version : 2.4.4 [402040402] (G-7617c2c6-2022-10-12 16:14:18 +0200)
SDK Version : 1.4.27 (7617c2c6)
Phone : ONEPLUS A6013 (2111252327 11 REL)
Memory statuses
usedSize 9 MB
freeSize 246 MB
totalSize 256 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: java.lang.RuntimeException: /data/user/0/fr.gouv.tchap.a/files/9b858e4a0e974a6ff8f76cca92df34c4/disk_store.realm: Encrypted interprocess sharing is currently unsupported.DB has been opened by pid: 12261. Current pid is 15307. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7029)
at android.app.ActivityThread.access$1700(ActivityThread.java:274)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2098)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:233)
at android.app.ActivityThread.main(ActivityThread.java:8068)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.RuntimeException: /data/user/0/fr.gouv.tchap.a/files/9b858e4a0e974a6ff8f76cca92df34c4/disk_store.realm: Encrypted interprocess sharing is currently unsupported.DB has been opened by pid: 12261. Current pid is 15307. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:11)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
at io.realm.BaseRealm.<init>(BaseRealm.java:26)
at io.realm.Realm.<init>(Realm.java:8)
at io.realm.RealmCache.createInstance(RealmCache.java:2)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:16)
at io.realm.Realm.getInstance(Realm.java:4)
at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:34)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:1)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
at org.matrix.android.sdk.internal.session.DaggerSessionComponent$SessionComponentImpl.session(DaggerSessionComponent.java:1)
at org.matrix.android.sdk.internal.SessionManager.getLastSession(SessionManager.kt:2)
at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:1)
at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:88)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7024)
... 8 more

User-Agent: "Tchap/2.4.4 (Linux; U; Android 11; ONEPLUS A6013 Build/RKQ1.201217.00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.4 [402040402] (G-7617c2c6-2022-10-12 16:14:18 +0200)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "ONEPLUS A6013"
device_id: "VPHMZJQQIO"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7617c2c6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "11 (API 30) 2111252327-REL"
server_version: "undefined"
theme: "light"
