### ISSUE TITLE
Crash - by clicking on a notification: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android#585]
### Steps to reproduce

crash call stack ---------------------------------
Element Build : 40202012
Element Version : 2.2.1 [40202012] (G-67e09ba3-2022-04-19 11:07:51 +0200)
SDK Version : 1.4.8 (67e09ba3)
Phone : SM-G950F
Memory statuses
usedSize 8 MB
freeSize 6 MB
totalSize 15 MB
Thread: main, Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:504)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:494)
... 1 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.airbnb.mvrx.MavericksFactory.create(MavericksFactory.kt:12)
at com.airbnb.mvrx.MavericksViewModelProvider.get$default(MavericksViewModelProvider.kt:34)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke(MavericksExtensions.kt:10)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke(MavericksExtensions.kt:1)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:2)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:1)
at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:5)
at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate(lifecycleAwareLazy.kt:1)
at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:8)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:9)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
at android.app.Activity.performStart(Activity.java:7348)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3138)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7050)
... 3 more
Caused by: java.lang.NullPointerException
at im.vector.app.features.home.room.detail.TimelineViewModel.<init>(TimelineViewModel.kt:18)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModelCImpl$SwitchingProvider$86.create(DaggerVectorApplication_HiltComponents_SingletonC.java:16)
at im.vector.app.core.di.HiltMavericksViewModelFactory.create(HiltMavericksViewModelFactory.kt:6)
at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create(Unknown Source:14)
at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create(TimelineViewModel.kt:1)
... 37 more

User-Agent: "Tchap/2.2.1 (Linux; U; Android 9; SM-G950F Build/PPR1.180610.01; Flavour GooglePlay; MatrixAndroidSdk2 1.4.8)"
Version: "2.2.1 [40202012] (G-67e09ba3-2022-04-19 11:07:51 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G950F"
locale: "fr_FR"
matrix_sdk_version: "1.4.8 (67e09ba3)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "9 (API 28)"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

#### What happened instead?
Crash notification by clicking on a notification :
The user received a private message.
He pressed the notification but the application did not launch.
He got the message "Tchap is not responding".
He closed and restarted Tchap.
This worked. 

### Your phone model

SM-G950F

### Operating system version

 Android 9

### Application version and app store

2.2.1

### Will you send logs?

No

**Comment by jdauphant** [comment]
Same as https://github.com/vector-im/element-android/issues/717

**Comment by jdauphant** [comment]
+1 in 2.3.2

**Comment by jdauphant** [comment]
crash call stack ---------------------------------
Element Build : 40203022
Element Version : 2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)
SDK Version : 1.4.11 (8861a9e7)
Phone : SM-G398FN (G398FNXXSGCVG1 11 REL)
Memory statuses
usedSize 25 MB
freeSize 166 MB
totalSize 192 MB
Thread: main, Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:612)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:602)
... 1 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.airbnb.mvrx.MavericksFactory.create(MavericksFactory.kt:12)
at com.airbnb.mvrx.MavericksViewModelProvider.get$default(MavericksViewModelProvider.kt:34)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke(MavericksExtensions.kt:10)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke(MavericksExtensions.kt:1)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:2)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:1)
at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:5)
at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate(lifecycleAwareLazy.kt:1)
at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:8)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:9)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
at android.app.Activity.performStart(Activity.java:8231)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3864)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8645)
... 3 more
Caused by: java.lang.NullPointerException
at im.vector.app.features.home.room.detail.TimelineViewModel.<init>(TimelineViewModel.kt:19)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModelCImpl$SwitchingProvider$86.create(DaggerVectorApplication_HiltComponents_SingletonC.java:18)
at im.vector.app.core.di.HiltMavericksViewModelFactory.create(HiltMavericksViewModelFactory.kt:6)
at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create(Unknown Source:13)
at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create(TimelineViewModel.kt:1)
... 37 more

User-Agent: "Tchap/2.3.2 (Linux; U; Android 11; SM-G398FN Build/RP1A.200720..01; Flavour GooglePlay; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G398FN"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (8861a9e7)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "11 (API 30) G398FNXXSGCVG1-REL"
server_version: "undefined"
theme: "system"

**Comment by jdauphant** [comment]
"J'ai dans le doute relancé mon téléphone, ça le faisait a nouveau en accédant via un raccourci direct vers un salon. "
@yostyle @Florian14 @giomfo  Apparently it's a problem with android home shortcut

**Comment by jdauphant** [comment]
"Durant plusieurs minutes, lorsque je lançais l’appli en cliquant sur la notification d’un message reçu, elle se fermait immédiatement.

Par contre, lorsque je lançais l’appli directement depuis son icone, tout fonctionnait."

Apparently the crash can append with direct access from notification

**Comment by Nivann** [comment]
Toujours présent sur la 2.4.2

crash call stack ---------------------------------
Element Build : 40204022
Element Version : 2.4.2 [40204022] (G-dc462ebb-2022-08-29 15:54:43 +0200)
SDK Version : 1.4.27 (dc462ebb)
Phone : SM-G950F 
Memory statuses
usedSize 8 MB
freeSize 1 MB
totalSize 9 MB
Thread: main, Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:504)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:494)
... 1 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.airbnb.mvrx.MavericksFactory.create(MavericksFactory.kt:12)
at com.airbnb.mvrx.MavericksViewModelProvider.get$default(MavericksViewModelProvider.kt:34)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke(MavericksExtensions.kt:10)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke(MavericksExtensions.kt:1)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:2)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:1)
at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:5)
at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate(lifecycleAwareLazy.kt:1)
at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:8)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:9)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
at android.app.Activity.performStart(Activity.java:7348)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3138)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7050)
... 3 more
Caused by: java.lang.NullPointerException
at im.vector.app.features.home.room.detail.TimelineViewModel.<init>(TimelineViewModel.kt:21)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModelCImpl$SwitchingProvider$87.create(DaggerVectorApplication_HiltComponents_SingletonC.java:20)
at im.vector.app.core.di.HiltMavericksViewModelFactory.create(HiltMavericksViewModelFactory.kt:6)
at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create(Unknown Source:14)
at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create(TimelineViewModel.kt:1)
... 37 more

User-Agent: "Tchap/2.4.2 (Linux; U; Android 9; SM-G950F Build/PPR1.180610.01; Flavour GooglePlay; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.2 [40204022] (G-dc462ebb-2022-08-29 15:54:43 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G950F"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (dc462ebb)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "9 (API 28) 
server_version: "undefined"
theme: "system"
verbose_log: "OFF"
