### ISSUE TITLE
Exception: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: java.lang.RuntimeException

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android#590]
### Steps to reproduce

crash call stack ---------------------------------
Element Build : 40202012
Element Version : 2.2.1 [40202012] (G-67e09ba3-2022-04-19 11:07:51 +0200)
SDK Version : 1.4.8 (67e09ba3)
Phone : AC2003
Memory statuses
usedSize 18 MB
freeSize 237 MB
totalSize 256 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: java.lang.RuntimeException: /data/user/0/fr.gouv.tchap.a/files/dd6e1f6e385c4866538d9a70d0194481/disk_store.realm: Encrypted interprocess sharing is currently unsupported.DB has been opened by pid: 4468. Current pid is 7045. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7005)
at android.app.ActivityThread.access$1800(ActivityThread.java:270)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2100)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:245)
at android.app.ActivityThread.main(ActivityThread.java:8024)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:631)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.RuntimeException: /data/user/0/fr.gouv.tchap.a/files/dd6e1f6e385c4866538d9a70d0194481/disk_store.realm: Encrypted interprocess sharing is currently unsupported.DB has been opened by pid: 4468. Current pid is 7045. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:11)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
at io.realm.BaseRealm.<init>(BaseRealm.java:26)
at io.realm.Realm.<init>(Realm.java:8)
at io.realm.RealmCache.createInstance(RealmCache.java:2)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:16)
at io.realm.Realm.getInstance(Realm.java:4)
at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:38)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:1)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
at org.matrix.android.sdk.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:1)
at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:3)
at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:91)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7000)
... 8 more

User-Agent: "Tchap/2.2.1 (Linux; U; Android 11; AC2003 Build/RP1A.201005.00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.8)"
Version: "2.2.1 [40202012] (G-67e09ba3-2022-04-19 11:07:51 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "AC2003"
locale: "fr_FR"
matrix_sdk_version: "1.4.8 (67e09ba3)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "11 (API 30)"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

### Outcome

The application keeps crashing and makes my device slow down a lot.

The problem is that I don't use the app when it crashes and makes my phone slow down a lot.

My phone slows down and sometimes gives me a black screen. When the black screen ends, chatting tells me it has crashed.

### Your phone model

AC2003

### Operating system version

Android 11

### Application version and app store

olm_version: "3.2.10 - olm version (3.2.8)

### Will you send logs?

Yes

**Comment by Claire1817** [comment]
Same bug here: https://github.com/tchapgouv/tchap-android/issues/583
