### ISSUE TITLE
Crash -  Exception: java.lang.RuntimeException: Unable to start activity - Core-X4 NEO

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#640]
### Steps to reproduce

Crash lors de l'ouverture de l'application 

crash call stack ---------------------------------
Element Build : 402000422
Element Version : 2.0.4 [402000422] (F-275f7fda-2022-05-05 11:59:48 +0200)
SDK Version : 1.3.12 (275f7fda)
Phone : Core-X4 NEO
Memory statuses
usedSize 5 MB
freeSize 0 MB
totalSize 5 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.gouv.tchap.a/im.vector.app.features.share.IncomingShareActivity}: java.lang.IllegalStateException: You should authenticate before using this
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3432)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7705)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: java.lang.IllegalStateException: You should authenticate before using this
at im.vector.app.core.di.ActiveSessionHolder.getActiveSession(ActiveSessionHolder.kt:2)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC.-$$Nest$msession(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$ActivityCImpl.roomSummaryItemFactory(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$ActivityCImpl$SwitchingProvider.get(DaggerVectorApplication_HiltComponents_SingletonC.java:14)
at im.vector.app.core.di.VectorFragmentFactory.instantiate(VectorFragmentFactory.kt:11)
at androidx.fragment.app.FragmentTransaction.createFragment(FragmentTransaction.java:3)
at im.vector.app.core.extensions.ActivityKt.addFragment$default(Activity.kt:5)
at im.vector.app.features.share.IncomingShareActivity.initUiAndData(IncomingShareActivity.kt:2)
at im.vector.app.core.platform.VectorBaseActivity.onCreate(VectorBaseActivity.kt:32)
at android.app.Activity.performCreate(Activity.java:7994)
at android.app.Activity.performCreate(Activity.java:7978)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
... 11 more

User-Agent: "Tchap/2.0.4 (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID b3059d94d998356; Flavour FDroid; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.4 [402000422] (F-275f7fda-2022-05-05 11:59:48 +0200)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
device_id: "VNAHMPVHWV"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (275f7fda)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
server_version: "undefined"
theme: "system"

### Will you send logs?

Yes

**Comment by jdauphant** [comment]
crash call stack ---------------------------------
Element Build : 402030221
Element Version : 2.3.2 [402030221] (F-2351117a-2022-07-21 09:28:17 +0000)
SDK Version : 1.4.16 (2351117a)
Phone : Core-X4 NEO (2022071915 11 REL)
Memory statuses
usedSize 4 MB
freeSize 0 MB
totalSize 4 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.gouv.tchap.a/im.vector.app.features.share.IncomingShareActivity}: java.lang.IllegalStateException: You should authenticate before using this
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3432)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7705)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: java.lang.IllegalStateException: You should authenticate before using this
at im.vector.app.core.di.ActiveSessionHolder.getActiveSession(ActiveSessionHolder.kt:2)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.-$$Nest$msession(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$ActivityCImpl.roomSummaryItemFactory(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$ActivityCImpl$SwitchingProvider.get1(DaggerVectorApplication_HiltComponents_SingletonC.java:141)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$ActivityCImpl$SwitchingProvider.get(DaggerVectorApplication_HiltComponents_SingletonC.java:7)
at im.vector.app.core.di.VectorFragmentFactory.instantiate(VectorFragmentFactory.kt:21)
at androidx.fragment.app.FragmentTransaction.createFragment(FragmentTransaction.java:3)
at im.vector.app.core.extensions.ActivityKt.addFragment$default(Activity.kt:5)
at im.vector.app.features.share.IncomingShareActivity.initUiAndData(IncomingShareActivity.kt:2)
at im.vector.app.core.platform.VectorBaseActivity.onCreate(VectorBaseActivity.kt:34)
at android.app.Activity.performCreate(Activity.java:7994)
at android.app.Activity.performCreate(Activity.java:7978)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
... 11 more

User-Agent: "Tchap/2.4.3-dev (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID e224d96a642f2e5a; Flavour FDroid; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)"
app_language: "fr_FR"
can_contact: "false"
default_app_language: "fr_FR"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7466edf6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "11 (API 30) 2022100509-REL"
server_version: "undefined"
theme: "system"

**Comment by Nivann** [comment]
+ 1

**Comment by Nivann** [comment]
+1

crash call stack ---------------------------------
Element Build : 402000422
Element Version : 2.0.4 [402000422] (F-275f7fda-2022-05-05 11:59:48 +0200)
SDK Version : 1.3.12 (275f7fda)
Memory statuses
usedSize 19 MB
freeSize 492 MB
totalSize 512 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.gouv.tchap.a/im.vector.app.features.share.IncomingShareActivity}: java.lang.IllegalStateException: You should authenticate before using this
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3432)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7705)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: java.lang.IllegalStateException: You should authenticate before using this
at im.vector.app.core.di.ActiveSessionHolder.getActiveSession(ActiveSessionHolder.kt:2)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC.-$$Nest$msession(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$ActivityCImpl.roomSummaryItemFactory(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$ActivityCImpl$SwitchingProvider.get(DaggerVectorApplication_HiltComponents_SingletonC.java:14)
at im.vector.app.core.di.VectorFragmentFactory.instantiate(VectorFragmentFactory.kt:11)
at androidx.fragment.app.FragmentTransaction.createFragment(FragmentTransaction.java:3)
at im.vector.app.core.extensions.ActivityKt.addFragment$default(Activity.kt:5)
at im.vector.app.features.share.IncomingShareActivity.initUiAndData(IncomingShareActivity.kt:2)
at im.vector.app.core.platform.VectorBaseActivity.onCreate(VectorBaseActivity.kt:32)
at android.app.Activity.performCreate(Activity.java:7994)
at android.app.Activity.performCreate(Activity.java:7978)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
... 11 more

User-Agent: "Tchap/2.4.3-dev (Linux; U; Android 11;
Version: "2.4.3-dev [402040302]
app_language: "fr_FR"
can_contact: "false"
default_app_language: "fr_FR"

locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7466edf6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
server_version: "undefined"
theme: "system"

**Comment by yostyle** [comment]
Fixed by https://github.com/element-hq/element-android/pull/6548
