### ISSUE TITLE
Exception: java.lang.RuntimeException: setDataSource failed: status = 0x80000000

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#643]
crash call stack ---------------------------------
Element Build : 40202012
Element Version : 2.2.1 [40202012] (G-67e09ba3-2022-04-19 11:07:51 +0200)
SDK Version : 1.4.8 (67e09ba3)
Phone : SM-A515F 
Memory statuses
usedSize 18 MB
freeSize 16 MB
totalSize 35 MB
Thread: main, Exception: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
at android.media.MediaMetadataRetriever._setDataSource(Native Method)
at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:313)
at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:337)
at im.vector.lib.multipicker.utils.ContentResolverUtilKt.toMultiPickerVideoType(ContentResolverUtil.kt:11)
at im.vector.lib.multipicker.MediaPicker.getSelectedFiles(MediaPicker.kt:7)
at im.vector.app.features.attachments.AttachmentsHelper.onMediaResult(AttachmentsHelper.kt:3)
at im.vector.app.features.home.room.detail.TimelineFragment$attachmentMediaActivityResultLauncher$1.invoke(TimelineFragment.kt:4)
at im.vector.app.features.home.room.detail.TimelineFragment$attachmentMediaActivityResultLauncher$1.invoke(TimelineFragment.kt:5)
at im.vector.app.core.extensions.FragmentKt$$ExternalSyntheticLambda0.onActivityResult(R8$$SyntheticClass:2)
at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:12)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
at androidx.fragment.app.Fragment.performStart(Fragment.java:7)
at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:3)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:11)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:8)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:22)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
at android.app.Activity.performStart(Activity.java:8315)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

User-Agent: "Tchap/2.2.1 (Linux; U; Android 12; SM-A515F Build/SP1A.210812.01; Flavour GooglePlay; MatrixAndroidSdk2 1.4.8)"
Version: "2.2.1 [40202012] (G-67e09ba3-2022-04-19 11:07:51 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-A515F"
device_id: "WFNPBFJYCD"
locale: "fr_FR"
matrix_sdk_version: "1.4.8 (67e09ba3)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "12 (API 31) 
server_version: "undefined"
theme: "system"

**Comment by Claire1817** [comment]
Same issue on Element: https://github.com/vector-im/element-android/issues/3613
