### ISSUE TITLE
Crash - Exception: Canvas: trying to draw too large(192000000bytes) bitmap.

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android#683]
[tchap-android] [Element] L'application plante à l'ouverture d'une image

User message:

[Element] L'application plante à l'ouverture d'une image
 crash call stack ---------------------------------
Element Build : 402000422
Element Version : 2.0.4 [402000422] (F-275f7fda-2022-05-05 11:59:48 +0200)
SDK Version : 1.3.12 (275f7fda)
Phone : Core-X4 NEO (2022071915 11 REL)
Memory statuses
usedSize 19 MB
freeSize 16 MB
totalSize 35 MB
Thread: main, Exception: java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.
at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
at android.widget.ImageView.onDraw(ImageView.java:1436)
at android.view.View.draw(View.java:22354)
at android.view.View.updateDisplayListIfDirty(View.java:21230)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21221)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:1)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21221)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.draw(View.java:22357)
at android.view.View.updateDisplayListIfDirty(View.java:21230)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21221)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21221)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21221)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21221)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21221)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21221)
at android.view.View.draw(View.java:22085)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.draw(View.java:22357)
at com.android.internal.policy.DecorView.draw(DecorView.java:806)
at android.view.View.updateDisplayListIfDirty(View.java:21230)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4108)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3835)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3106)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1950)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8186)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
at android.view.Choreographer.doCallbacks(Choreographer.java:878)
at android.view.Choreographer.doFrame(Choreographer.java:811)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7705)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

User-Agent: "Tchap/2.0.4 (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID ba309e8cf6442620; Flavour FDroid; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.4 [402000422] (F-275f7fda-2022-05-05 11:59:48 +0200)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (275f7fda)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) 2022071915-REL"
server_version: "undefined"
theme: "system"
verbose_log: "OFF"

**Comment by Claire1817** [comment]
Issue comes from Element: https://github.com/vector-im/element-android/issues/3603

**Comment by jdauphant** [comment]
Element Version : 2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)
SDK Version : 1.4.11 (8861a9e7)
Phone : 2201116PG (V13.0.8.0.RKCEUXM 11 REL)
Memory statuses
usedSize 58 MB
freeSize 23 MB
totalSize 81 MB
Thread: main, Exception: java.lang.RuntimeException: Canvas: trying to draw too large(556902016bytes) bitmap.
at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
at android.widget.ImageView.onDraw(ImageView.java:1436)
at android.view.View.draw(View.java:22731)
at android.view.View.updateDisplayListIfDirty(View.java:21593)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.updateDisplayListIfDirty(View.java:21584)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:1)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.updateDisplayListIfDirty(View.java:21584)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.draw(View.java:22735)
at android.view.View.updateDisplayListIfDirty(View.java:21593)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.updateDisplayListIfDirty(View.java:21584)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.updateDisplayListIfDirty(View.java:21584)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.updateDisplayListIfDirty(View.java:21584)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.updateDisplayListIfDirty(View.java:21584)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.updateDisplayListIfDirty(View.java:21584)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.updateDisplayListIfDirty(View.java:21584)
at android.view.View.draw(View.java:22455)
at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
at android.view.View.draw(View.java:22735)
at com.android.internal.policy.DecorView.draw(DecorView.java:826)
at android.view.View.updateDisplayListIfDirty(View.java:21593)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:567)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:651)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4311)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4012)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2083)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8550)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
at android.view.Choreographer.doCallbacks(Choreographer.java:962)
at android.view.Choreographer.doFrame(Choreographer.java:887)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8163)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)

User-Agent: "Tchap/2.3.2 (Linux; U; Android 11; 2201116PG Build/RKQ1.211001..00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "2201116PG"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (8861a9e7)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "11 (API 30) V13.0.8.0.RKCEUXM-REL"

**Comment by yostyle** [comment]
It was fixed in https://github.com/vector-im/element-android/pull/6290
