### ISSUE TITLE
crash - java.util.ConcurrentModificationException at java.util.ArrayList$Itr.next(ArrayList.java:860)

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#691]
crash call stack ---------------------------------
Element Build : 40203022
Element Version : 2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)
SDK Version : 1.4.11 (8861a9e7)
Phone : SM-A528B 
Memory statuses
usedSize 45 MB
freeSize 10 MB
totalSize 56 MB
Thread: Crypto_Thread, Exception: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:860)
at org.matrix.android.sdk.internal.crypto.RoomDecryptorProvider$getOrCreateRoomDecryptor$alg$1$1.onNewSession(RoomDecryptorProvider.kt:3)
at org.matrix.android.sdk.internal.crypto.algorithms.megolm.MXMegolmDecryption.onNewSession(MXMegolmDecryption.kt:5)
at org.matrix.android.sdk.internal.crypto.algorithms.megolm.MXMegolmDecryption.onRoomKeyEvent(MXMegolmDecryption.kt:86)
at org.matrix.android.sdk.internal.crypto.DefaultCryptoService$onToDeviceEvent$1.invokeSuspend(DefaultCryptoService.kt:171)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.3.2 (Linux; U; Android 12; SM-A528B Build/SP1A.210812.01; Flavour GooglePlay; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-A528B"
device_id: "TEPSJSDUUA"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (8861a9e7)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "12 (API 31) "
server_version: "undefined"
theme: "system"

**Comment by yostyle** [comment]
It was fixed in https://github.com/vector-im/element-android/issues/5746
The fix is present in Tchap android 2.4.0
