### ISSUE TITLE
Crash com.android.internal.net.VpnConfig.underlyingNetworks' on a null object reference / 2.0.4

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android#696]
```
[Element] arrêt intempestif
 crash call stack ---------------------------------
Element Build : 402000422
Element Version : 2.0.4 [402000422] (F-275f7fda-2022-05-05 11:59:48 +0200)
SDK Version : 1.3.12 (275f7fda)
Memory statuses
usedSize 16 MB
freeSize 495 MB
totalSize 512 MB
Thread: WM.task-1, Exception: java.lang.NullPointerException: Attempt to read from field 'android.net.Network[] com.android.internal.net.VpnConfig.underlyingNetworks' on a null object reference
at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:2220)
at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1046)
at androidx.work.impl.constraints.trackers.NetworkStateTracker.getActiveNetworkState(NetworkStateTracker.java:1)
at androidx.work.impl.constraints.trackers.NetworkStateTracker.getInitialState(NetworkStateTracker.java:1)
at androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.java:11)
at androidx.work.impl.constraints.WorkConstraintsTracker.replace(WorkConstraintsTracker.java:7)
at androidx.work.impl.background.greedy.GreedyScheduler.schedule(GreedyScheduler.java:51)
at androidx.work.impl.Schedulers.schedule(Schedulers.java:26)
at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:82)
at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:5)
at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:1)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.connectivity.Vpn.getUnderlyingNetworks(Vpn.java:1896)
at com.android.server.ConnectivityService.getVpnUnderlyingNetworks(ConnectivityService.java:1335)
at com.android.server.ConnectivityService.getUnfilteredActiveNetworkState(ConnectivityService.java:1345)
at com.android.server.ConnectivityService.getActiveNetworkInfo(ConnectivityService.java:1443)
at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:822)

User-Agent: "Tchap/2.0.4 (Linux; U; Android 11;  Flavour FDroid; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.4 [402000422] (F-275f7fda-2022-05-05 11:59:48 +0200)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (275f7fda)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30)"
server_version: "undefined"
theme: "system"
```

**Comment by jdauphant** [comment]
Only seen on 2.0.4 for the moment

**Comment by Nivann** [comment]
+1 https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_6794e66d-ed5f-4324-9ac6-ab9721682bda/

**Comment by jdauphant** [comment]
@Nivann est-ce que ça se produit en 2.3.2 ?

**Comment by Nivann** [comment]
@jdauphant je n'ai pas vu de tickets avec ce bug en 2.3.2

**Comment by yostyle** [comment]
@jdauphant Cela s'est produit sur un appareil connecté à un VPN. Le crash s'est produit au niveau système.

**Comment by jdauphant** [comment]
Pourquoi on le reçoit en rageshake dans ce cas ? on peut y faire quelques chose ?

**Comment by yostyle** [comment]
> Pourquoi on le reçoit en rageshake dans ce cas ? on peut y faire quelques chose ?

je suppose que l'application a tenté une requête réseau en passant par le service VPN du système. Ce dernier a levé une exception qui est remonté jusqu'à l'application. Il nous manque l'appel venant de l'application.
Avez vous plus de logs ?

**Comment by jdauphant** [comment]
@yostyle j'ai 6 fois le crash et j'ai les rapport de log avec eux à chaque fois, j'envois ça dans le bon salon

**Comment by Nivann** [comment]
+1

**Comment by jdauphant** [comment]
@yostyle Il y a une mise à jour des appareils le 21 juillet, c'est peut être lié

**Comment by Nivann** [comment]
+1 https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_02646a2f-f3f9-47c1-b8a1-38603bcc836c/

**Comment by jdauphant** [comment]
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_c90a5133-a757-472a-b1f6-f7f1f92cc309/
en 2.3.2 : 
crash call stack ---------------------------------
Element Build : 402030221
Element Version : 2.3.2 [402030221] (F-2351117a-2022-07-21 09:28:17 +0000)
SDK Version : 1.4.16 (2351117a)
Phone : Core-X4 NEO (2022071915 11 REL)
Memory statuses
usedSize 6 MB
freeSize 505 MB
totalSize 512 MB
Thread: WM.task-1, Exception: java.lang.NullPointerException: Attempt to read from field 'android.net.Network[] com.android.internal.net.VpnConfig.underlyingNetworks' on a null object reference
at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:2220)
at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1046)
at androidx.work.impl.constraints.trackers.NetworkStateTracker.getActiveNetworkState(NetworkStateTracker.java:1)
at androidx.work.impl.constraints.trackers.NetworkStateTracker.getInitialState(Unknown Source:0)
at androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.java:11)
at androidx.work.impl.constraints.WorkConstraintsTracker.replace(WorkConstraintsTracker.java:7)
at androidx.work.impl.background.greedy.GreedyScheduler.schedule(GreedyScheduler.java:50)
at androidx.work.impl.Schedulers.schedule(Schedulers.java:26)
at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:82)
at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:5)
at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:1)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.connectivity.Vpn.getUnderlyingNetworks(Vpn.java:1896)
at com.android.server.ConnectivityService.getVpnUnderlyingNetworks(ConnectivityService.java:1335)
at com.android.server.ConnectivityService.getUnfilteredActiveNetworkState(ConnectivityService.java:1345)
at com.android.server.ConnectivityService.getActiveNetworkInfo(ConnectivityService.java:1443)
at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:822)

User-Agent: "Tchap/2.3.2 (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID 2f66cf5b82dd47c3; Flavour FDroid; MatrixAndroidSdk2 1.4.16)"
Version: "2.3.2 [402030221] (F-2351117a-2022-07-21 09:28:17 +0000)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
locale: "fr_FR"
matrix_sdk_version: "1.4.16 (2351117a)"
multi_window: "OFF"
olm_version: "3.2.11 - olm version (3.2.8) - 2f23d99-2022-04-08 16:00:24 -0400"
os: "11 (API 30) 2022071915-REL"
server_version: "undefined"
theme: "system"

**Comment by jdauphant** [comment]
@yostyle @Florian14 The neo still have multiple crash link to VPN.
Does the 2.4 will be more robust on that problem ?

**Comment by estellecomment** [comment]
+2 on 2.3.2

**Comment by estellecomment** [comment]
+1 on 2.3.2 with this screenshot :
![screenshot](https://user-images.githubusercontent.com/911434/186126947-6ebfed3c-a80d-4e31-8674-ec74e87c09a1.png)

**Comment by odelcroi** [comment]
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_d1557680-7c33-4a1b-bcef-4cb0966ac2d2/

**Comment by odelcroi** [comment]
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_461d4194-4295-4573-9a5e-117770413b79/
