### ISSUE TITLE
Crash - Exception: java.util.ConcurrentModificationException (Normally Fixed in 2.4.2)

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#705]
crash call stack ---------------------------------
Element Build : 402030221
Element Version : 2.3.2 [402030221] (F-2351117a-2022-07-21 09:28:17 +0000)
SDK Version : 1.4.16 (2351117a)
Phone : Core-X4 NEO 
Memory statuses
usedSize 21 MB
freeSize 8 MB
totalSize 29 MB
Thread: epoxy, Exception: java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
at java.util.AbstractMap.putAll(AbstractMap.java:280)
at java.util.TreeMap.putAll(TreeMap.java:328)
at im.vector.app.features.roomdirectory.PublicRoomsController.buildModels(PublicRoomsController.kt:13)
at im.vector.app.features.roomdirectory.PublicRoomsController.buildModels(PublicRoomsController.kt:1)
at com.airbnb.epoxy.TypedEpoxyController.buildModels(TypedEpoxyController.java:2)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:6)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.3.2 (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID 5a4795f0c7539a24; Flavour FDroid; MatrixAndroidSdk2 1.4.16)"
Version: "2.3.2 [402030221] (F-2351117a-2022-07-21 09:28:17 +0000)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
device_id: "KJJIAWWXGT"
locale: "fr_FR"
matrix_sdk_version: "1.4.16 (2351117a)"
multi_window: "OFF"
olm_version: "3.2.11 - olm version (3.2.8) - 2f23d99-2022-04-08 16:00:24 -0400"
os: "11 (API 30)"
server_version: "undefined"
theme: "system"

**Comment by Nivann** [comment]
Crash when making a public forum search

**Comment by Nivann** [comment]
+1

**Comment by jdauphant** [comment]
+3
Look's like it's fixed on Element and Tchap v2.4 :  https://github.com/vector-im/element-android/pull/6469

**Comment by estellecomment** [comment]
+1 Neo tchap 2.3.2

**Comment by jdauphant** [comment]
Normally Fixed in 2.4.2
