### ISSUE TITLE
Crash-  Exception: Package android does not belong to 10166

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#709]
crash call stack ---------------------------------
Element Build : 40203012
Element Version : 2.3.1-dev [40203012] (F-6df2973d-2022-05-30 08:48:49 +0200)
SDK Version : 1.4.11 (6df2973d)
Memory statuses
usedSize 17 MB
freeSize 17 MB
totalSize 35 MB
Thread: SyncThread, Exception: java.lang.SecurityException: Package android does not belong to 10166
at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at android.net.IConnectivityManager$Stub$Proxy.requestNetwork(IConnectivityManager.java:3579)
at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3735)
at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4238)
at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4205)
at org.matrix.android.sdk.internal.network.PreferredNetworkCallbackStrategy.register(NetworkCallbackStrategy.kt:2)
at org.matrix.android.sdk.internal.network.DefaultNetworkConnectivityChecker.register(NetworkConnectivityChecker.kt:3)
at org.matrix.android.sdk.internal.session.sync.job.SyncThread.run(SyncThread.kt:6)
Caused by: android.os.RemoteException: Remote stack trace:
at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7739)
at com.android.server.ConnectivityService.ensureSufficientPermissionsForRequest(ConnectivityService.java:5515)
at com.android.server.ConnectivityService.requestNetwork(ConnectivityService.java:5610)
at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:1601)
at android.os.Binder.execTransactInternal(Binder.java:1154)

User-Agent: "Tchap/2.3.1-dev (Linux; U; Android 11; Flavour FDroid; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.1-dev [40203012] (F-6df2973d-2022-05-30 08:48:49 +0200)"
app_language: "fr_FR"
can_contact: "true"
default_app_language: "fr_FR"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (6df2973d)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "11 (API 30)"
server_version: "undefined"
theme: "system"

**Comment by estellecomment** [comment]
+1 
Sur la page "Vos salons seront affichés ici" (page de loading des salons ?)

Element Build : 402040302
Element Version : 2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)
SDK Version : 1.4.27 (7466edf6)
Phone : Core-X4 NEO (2022100509 11 REL)
Memory statuses
usedSize 10 MB
freeSize 5 MB
totalSize 15 MB
Thread: SyncThread, Exception: java.lang.SecurityException: Package android does not belong to 10127
at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at android.net.IConnectivityManager$Stub$Proxy.requestNetwork(IConnectivityManager.java:3579)
at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3735)
at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4238)
at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4205)
at org.matrix.android.sdk.internal.network.PreferredNetworkCallbackStrategy.register(NetworkCallbackStrategy.kt:2)
at org.matrix.android.sdk.internal.network.DefaultNetworkConnectivityChecker.register(NetworkConnectivityChecker.kt:3)
at org.matrix.android.sdk.internal.session.sync.job.SyncThread.run(SyncThread.kt:6)
Caused by: android.os.RemoteException: Remote stack trace:
at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7739)
at com.android.server.ConnectivityService.ensureSufficientPermissionsForRequest(ConnectivityService.java:5540)
at com.android.server.ConnectivityService.requestNetwork(ConnectivityService.java:5635)
at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:1601)
at android.os.Binder.execTransactInternal(Binder.java:1154)

User-Agent: "Tchap/2.4.3-dev (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID 9f8ee1121b9fcd86; Flavour FDroid; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)"
app_language: "fr_FR"
branch_name: "develop-ssi-neo"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
device_id: "LRDDENQBIU"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7466edf6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "11 (API 30) 2022100509-REL"
server_version: "undefined"
theme: "system"
user_id: "<redacted>"
verbose_log: "OFF"

**Comment by estellecomment** [comment]
related : 
https://github.com/tchapgouv/tchap-android/issues/702
https://github.com/tchapgouv/tchap-android/issues/644
https://github.com/tchapgouv/tchap-android/issues/571
