### ISSUE TITLE
Crash - Exception: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-1

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#710]
crash call stack ---------------------------------
Element Build : 40203022
Element Version : 2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)
SDK Version : 1.4.11 (8861a9e7)
Phone : SM-G9350 
Memory statuses
usedSize 39 MB
freeSize 9 MB
totalSize 48 MB
Thread: main, Exception: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-1
at android.text.DynamicLayout.getBlockIndex(DynamicLayout.java:646)
at android.widget.Editor.drawHardwareAccelerated(Editor.java:1820)
at android.widget.Editor.onDraw(Editor.java:1789)
at android.widget.TextView.onDraw(TextView.java:7763)
at android.view.View.draw(View.java:20370)
at android.view.View.updateDisplayListIfDirty(View.java:19315)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19274)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

User-Agent: "Tchap/2.3.2 (Linux; U; Android 8.0.0; SM-G9350 Build/R16N; Flavour GooglePlay; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G9350"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (8861a9e7)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "8.0.0 (API 26)
server_version: "undefined"
theme: "dark"
verbose_log: "OFF"

**Comment by Florian14** [comment]
Hi @Nivann, do you have other occurrences of this crash? We need more context to investigate it, the stacktrace is too low level to be helpful for debugging.

**Comment by Nivann** [comment]
Hello @Florian14, here is the description of the crash by the user : 

"J'ai reproduit le problème deux fois sur le même message :

Il est dans le salon "apps.education.fr" le 14 aout.

J'ai commencé à rédiger le message, j'ai ajouté le lien. J'ai ajouté l’émoticône. J'ai voulu ajouter le mot "toujours". Et là : plantage (je ne me souviens plus du message d'erreur). Tchap s’arrête et repart avec le message déjà rédigé, mais sans le lien, sans l'émoticone et sans le mot "toujours".

J'ai refait la manipulation dans le même ordre deux fois, et le plantage s'est reproduit à chaque fois.

La quatrième fois, j'ai commencé à ajouter le mot en premier, et ça a fonctionné."

**Comment by Nivann** [comment]
@Florian14 I can send you the logs

**Comment by jdauphant** [comment]
[tchap] Crash dans un salon (15 personnes) lorsque l'on essaie de répondre à un message spécifique et absence de mise a jour des messages non lus.
 crash call stack ---------------------------------
Element Build : 402040302
Element Version : 2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)
SDK Version : 1.4.27 (7466edf6)
Phone : Xperia XA2 (AOSP) (eng.270920.20220912.130941 8.1.0 REL)
Memory statuses
usedSize 37 MB
freeSize 9 MB
totalSize 47 MB
Thread: main, Exception: java.lang.ArrayIndexOutOfBoundsException: length=290; index=-16
at android.text.Layout.ellipsize(Layout.java:2225)
at android.text.Layout.-wrap2(Unknown Source:0)
at android.text.Layout$Ellipsizer.getChars(Layout.java:2299)
at android.text.TextUtils.getChars(TextUtils.java:100)
at android.graphics.Paint.getRunAdvance(Paint.java:2765)
at android.text.TextLine.getRunAdvance(TextLine.java:827)
at android.text.TextLine.handleText(TextLine.java:873)
at android.text.TextLine.handleRun(TextLine.java:1213)
at android.text.TextLine.drawRun(TextLine.java:493)
at android.text.TextLine.draw(TextLine.java:226)
at android.text.Layout.drawText(Layout.java:539)
at android.text.Layout.draw(Layout.java:286)
at android.widget.TextView.onDraw(TextView.java:6901)
at android.view.View.draw(View.java:19192)
at android.view.View.updateDisplayListIfDirty(View.java:18142)
at android.view.View.draw(View.java:18920)
at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
at android.view.View.draw(View.java:19195)
at android.view.View.updateDisplayListIfDirty(View.java:18142)
at android.view.View.draw(View.java:18920)
at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
at android.view.View.updateDisplayListIfDirty(View.java:18133)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
at android.view.View.updateDisplayListIfDirty(View.java:18101)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2989)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2803)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2356)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1389)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6749)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6500)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

User-Agent: "Tchap/2.4.3-dev (Linux; U; Android 8.1.0; Xperia XA2 (AOSP) Build/OPM7.181205.00; Flavour FDroid; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)"
app_language: "fr_FR"
branch_name: "develop-ssi-neo"
can_contact: "true"
default_app_language: "fr_FR"
device: "Xperia XA2 (AOSP)"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7466edf6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "8.1.0 (API 27) eng.270920.20220912.130941-REL"
server_version: "undefined"
theme: "system"

**Comment by jdauphant** [comment]
[tchap] en train d'envoyer un message, plantage pendant la rédaction
 crash call stack ---------------------------------
Element Build : 402040402
Element Version : 2.4.4 [402040402] (G-7617c2c6-2022-10-12 16:14:18 +0200)
SDK Version : 1.4.27 (7617c2c6)
Phone : SM-G930F (G930FXXU8EVG3 8.0.0 REL)
Memory statuses
usedSize 43 MB
freeSize 6 MB
totalSize 50 MB
Thread: main, Exception: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-1
at android.text.DynamicLayout.getBlockIndex(DynamicLayout.java:646)
at android.widget.Editor.drawHardwareAccelerated(Editor.java:1820)
at android.widget.Editor.onDraw(Editor.java:1789)
at android.widget.TextView.onDraw(TextView.java:7779)
at android.view.View.draw(View.java:20373)
at android.view.View.updateDisplayListIfDirty(View.java:19318)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
at android.view.View.updateDisplayListIfDirty(View.java:19277)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

User-Agent: "Tchap/2.4.4 (Linux; U; Android 8.0.0; SM-G930F Build/R16N; Flavour GooglePlay; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.4 [402040402] (G-7617c2c6-2022-10-12 16:14:18 +0200)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device_id: "WEEMABGHIM"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7617c2c6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "8.0.0 (API 26) G930FXXU8EVG3-REL"
server_version: "undefined"
theme: "dark"

**Comment by AmelAlili** [comment]
+1

tchap-android] [tchap] Ça plante très souvent lors de l'ajout d'une emoticone.

User message:

[tchap] Ça plante très souvent lors de l'ajout d'une emoticone.
 crash call stack ---------------------------------
Element Build : 402040402
Element Version : 2.4.4 [402040402] (G-7617c2c6-2022-10-12 16:14:18 +0200)
SDK Version : 1.4.27 (7617c2c6)
Phone : WAS-TL10 (371(C636) 8.0.0 REL)
Memory statuses
usedSize 21 MB
freeSize 0 MB
totalSize 22 MB
Thread: main, Exception: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-1
at android.text.DynamicLayout.getBlockIndex(DynamicLayout.java:646)
at android.widget.Editor.drawHardwareAccelerated(Editor.java:1744)
at android.widget.Editor.onDraw(Editor.java:1713)
at android.widget.TextView.onDraw(TextView.java:7051)
at android.view.View.draw(View.java:19314)
at android.view.View.updateDisplayListIfDirty(View.java:18250)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
at android.view.View.updateDisplayListIfDirty(View.java:18209)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:684)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:804)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3206)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3004)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2533)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7292)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
at android.view.Choreographer.doCallbacks(Choreographer.java:790)
at android.view.Choreographer.doFrame(Choreographer.java:721)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:7529)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

User-Agent: "Tchap/2.4.4 (Linux; U; Android 8.0.0; WAS-TL10 Build/HUAWEIWAS-TL1; Flavour GooglePlay; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.4 [402040402] (G-7617c2c6-2022-10-12 16:14:18 +0200)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "WAS-TL10"
device_id: "DOCSAPMNTH"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7617c2c6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "8.0.0 (API 26) 371(C636)-REL"
server_version: "undefined"
theme: "system"
