### ISSUE TITLE
Crash - Exception: java.util.ConcurrentModificationException at java.util.ArrayList$Itr.next(ArrayList.java:860)

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android#729]
crash call stack ---------------------------------
Element Build : 40203022
Element Version : 2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)
SDK Version : 1.4.11 (8861a9e7)
Phone : CPH2025 (Q.GDPR.202207291615 12 REL)
Memory statuses
usedSize 52 MB
freeSize 6 MB
totalSize 59 MB
Thread: Crypto_Thread, Exception: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:860)
at org.matrix.android.sdk.internal.crypto.RoomDecryptorProvider$getOrCreateRoomDecryptor$alg$1$1.onNewSession(RoomDecryptorProvider.kt:3)
at org.matrix.android.sdk.internal.crypto.algorithms.megolm.MXMegolmDecryption.onNewSession(MXMegolmDecryption.kt:5)
at org.matrix.android.sdk.internal.crypto.algorithms.megolm.MXMegolmDecryption.onRoomKeyEvent(MXMegolmDecryption.kt:86)
at org.matrix.android.sdk.internal.crypto.DefaultCryptoService$onToDeviceEvent$1.invokeSuspend(DefaultCryptoService.kt:171)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.3.2 (Linux; U; Android 12; CPH2025 Build/RKQ1.211103.00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.2 [40203022] (G-8861a9e7-2022-07-04 16:34:08 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "CPH2025"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (8861a9e7)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "12 (API 31) Q.GDPR.202207291615-REL"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

> J’utilise régulièrement le client Element pour la messagerie Tchap, sauf quand je dois inviter de nouveaux contacts.
> Du coup je me suis connecté sur Tchap Windows et sur Element ca m’a demandé de vérifier une session, j’ai tenté de déclencher la vérification mais je n’ai rien vu sur Tchap web. Sur le Tchap Web, je ne voyais pas les messages, ils étaient cryptés, j’ai fait une demande de resynchronisation des clés mais ça n’a rien changé
> DU coup je me suis dit qu’il fallait aller sur le client Mobile
> Je me suis donc connecté sur tchap Android, j’avais des messages cryptés là aussi, et pendant qu’il devait tenter de recevoir les clé de mon client Element j’imagine, il y a eu le crash.
> J’y suis ensuite retourné et depuis ca semble fonctionner correctement…

**Comment by giomfo** [comment]
Related to https://github.com/vector-im/element-android/issues/5746

**Comment by jdauphant** [comment]
@Nivann @AmelAlili est-ce que c'est encore remonté ?
