### ISSUE TITLE
Crash - Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.gouv.tchap.a/im.vector.app.features.home.room.detail.RoomDetailActivity}:

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#732]
Crash lorsque l'utilisateur ouvre un salon 

crash call stack ---------------------------------
Element Build : 40204021
Element Version : 2.4.2 [40204021] (G-dc462ebb-2022-08-29 15:54:43 +0200)
SDK Version : 1.4.27 (dc462ebb)
Phone : SM-J320F
Memory statuses
usedSize 34 MB
freeSize 10 MB
totalSize 45 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.gouv.tchap.a/im.vector.app.features.home.room.detail.RoomDetailActivity}: java.lang.reflect.InvocationTargetException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3160)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3275)
at android.app.ActivityThread.access$1000(ActivityThread.java:218)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:7007)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.airbnb.mvrx.MavericksFactory.create(MavericksFactory.kt:12)
at com.airbnb.mvrx.MavericksViewModelProvider.get$default(MavericksViewModelProvider.kt:34)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$3.invoke(MavericksExtensions.kt:10)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$3.invoke(MavericksExtensions.kt:1)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:2)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:1)
at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:5)
at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate(lifecycleAwareLazy.kt:1)
at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:8)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:9)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1264)
at android.app.Activity.performStart(Activity.java:6647)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
... 10 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "opus_projection_encoder_ctl" referenced by "libopusenc.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:988)
at im.vector.opusencoder.OggOpusEncoder.<clinit>(OggOpusEncoder.kt:1)
at im.vector.app.features.voice.VoiceRecorderL.<init>(VoiceRecorderL.kt:4)
at im.vector.app.features.voice.VoiceRecorderProvider.provideVoiceRecorder(VoiceRecorderProvider.kt:5)
at im.vector.app.features.home.room.detail.composer.AudioMessageHelper.<init>(AudioMessageHelper.kt:4)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModelCImpl$SwitchingProvider$88.create(DaggerVectorApplication_HiltComponents_SingletonC.java:5)
at im.vector.app.core.di.HiltMavericksViewModelFactory.create(HiltMavericksViewModelFactory.kt:6)
at im.vector.app.features.home.room.detail.composer.MessageComposerViewModel$Companion.create(MessageComposerViewModel.kt)
at im.vector.app.features.home.room.detail.composer.MessageComposerViewModel$Companion.create(MessageComposerViewModel.kt:1)
... 37 more

User-Agent: "Tchap/2.4.2 (Linux; U; Android 5.1.1; SM-J320F Build/LMY47; Flavour GooglePlay; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.2 [40204021] (G-dc462ebb-2022-08-29 15:54:43 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-J320F"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (dc462ebb)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "5.1.1 (API 22) J320FXXU0AQL1-REL"
server_version: "undefined"
theme: "system"
verbose_log: "OFF"

**Comment by jdauphant** [comment]
duplicated #734

**Comment by Delphgateau** [comment]
+ 1 : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_6169b8a0-f79d-42de-8bd7-d581c3f18784/
"en cliquant sur un message arrivé dans la barre du haut, l'ouverture de l'application a rencontré des problèmes d'ouverture. cela a fait fermer l'application"
