### ISSUE TITLE
[Crash] - Exception: PrecomputedText's Parameters don't match the parameters of this TextView

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android#733]
User message:

[tchap] sur les [salons....il](http://salons....il/) y a un alignements de chifres et de lettres imcomprensible. je n arrive pas a vous envoyer la capture d ecran

 crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : SM-G960F (G960FXXU8DTC5 10 REL)
Memory statuses
usedSize 28 MB
freeSize 1 MB
totalSize 30 MB
Thread: main, Exception: java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using setTextMetricsParams(precomputedText.getParams()) to override the settings of this TextView: PrecomputedText: {textSize=36.75, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR], typeface=android.graphics.Typeface@6da7e43c, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@d882007, breakStrategy=1, hyphenationFrequency=0}TextView: {textSize=115.5, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR], typeface=android.graphics.Typeface@6da7e43c, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@d882007, breakStrategy=1, hyphenationFrequency=0}
at android.widget.TextView.setText(TextView.java:6731)
at android.widget.TextView.setText(TextView.java:6649)
at android.widget.TextView.setText(TextView.java:6601)
at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:4)
at androidx.appcompat.widget.AppCompatTextView.consumeTextFutureAndSetBlocking(AppCompatTextView.java:3)
at androidx.appcompat.widget.AppCompatTextView.getText(AppCompatTextView.java:1)
at androidx.emoji2.viewsintegration.EmojiInputFilter.filter(EmojiInputFilter.java:4)
at android.widget.TextView.setText(TextView.java:6685)
at android.widget.TextView.setText(TextView.java:6649)
at android.widget.TextView.setText(TextView.java:6601)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:44)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:6)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:25)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:3)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:131)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:13)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7857)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

User-Agent: "Tchap/2.4.2 (Linux; U; Android 10; SM-G960F Build/QP1A.190711.02; Flavour GooglePlay; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.2 [40204022] (G-dc462ebb-2022-08-29 15:54:43 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "true"
default_app_language: "fr_FR"
device: "SM-G960F"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (dc462ebb)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "10 (API 29) G960FXXU8DTC5-REL"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

**Comment by JDixmier** [comment]
> Depuis deux jours sous chaque salon j'ai un ensemble de chiffres et lettres incompréhensibles sur mon tph perso, alors que sur mon pro tout est ok.
> 
> Je n'ai pourtant pas fait de maj. J'ai bien redémarré mon tph mais le phénomène subsiste. Je vous joins le message d'erreur

**Comment by JDixmier** [comment]
![IMG_20220915_212402](https://user-images.githubusercontent.com/45665538/190987575-f9cb693a-c443-4dcd-880c-e4548896a728.jpg)

**Comment by JDixmier** [comment]
![IMG_20220915_212402](https://user-images.githubusercontent.com/45665538/190988219-c26944ca-0458-4ebf-9a92-49ab04541c53.jpg)
