### ISSUE TITLE
crash -  Exception: android.database.sqlite.SQLiteException: no such column: displayname (code 1 SQLITE_ERROR[1]): , while compiling: SELECT displayname, size FROM ClipboardImageTable WHERE (id=8) ORDER BY data

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#757]
arrêt subit de l'application pendant l'édition d'un message 

crash call stack ---------------------------------
Element Build : 40204022
Element Version : 2.4.2 [40204022] (G-dc462ebb-2022-08-29 15:54:43 +0200)
SDK Version : 1.4.27 (dc462ebb)
Phone : SM-G996B 
Memory statuses
usedSize 47 MB
freeSize 15 MB
totalSize 63 MB
Thread: main, Exception: android.database.sqlite.SQLiteException: no such column: displayname (code 1 SQLITE_ERROR[1]): , while compiling: SELECT displayname, size FROM ClipboardImageTable WHERE (id=8) ORDER BY data
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
at android.content.ContentResolver.query(ContentResolver.java:1226)
at android.content.ContentResolver.query(ContentResolver.java:1158)
at android.content.ContentResolver.query(ContentResolver.java:1114)
at im.vector.lib.multipicker.utils.ContentResolverUtilKt.toMultiPickerImageType(ContentResolverUtil.kt:2)
at im.vector.lib.multipicker.ImagePicker.getSelectedFiles(ImagePicker.kt:5)
at im.vector.lib.multipicker.Picker.getIncomingFiles(Picker.kt:12)
at im.vector.app.features.attachments.ShareIntentHandler.handleIncomingShareIntent(ShareIntentHandler.kt:4)
at im.vector.app.features.home.room.detail.TimelineFragment.sendUri(TimelineFragment.kt:2)
at im.vector.app.features.home.room.detail.TimelineFragment.access$sendUri(TimelineFragment.kt:1)
at im.vector.app.features.home.room.detail.TimelineFragment$setupComposer$2.onRichContentSelected(TimelineFragment.kt:1)
at im.vector.app.features.home.room.detail.composer.MessageComposerView$1.onRichContentSelected(MessageComposerView.kt:1)
at im.vector.app.features.home.room.detail.composer.ComposerEditText.onCreateInputConnection$lambda-1(ComposerEditText.kt:39)
at im.vector.app.features.home.room.detail.composer.ComposerEditText.$r8$lambda$r60CDknRi31d3-4DVi84wxqap50(Unknown Source:0)
at im.vector.app.features.home.room.detail.composer.ComposerEditText$$ExternalSyntheticLambda0.onReceiveContent(Unknown Source:2)
at androidx.core.view.ViewCompat$OnReceiveContentListenerAdapter.onReceiveContent(ViewCompat.java:2)
at android.view.View.performReceiveContent(View.java:9495)
at android.widget.TextView.paste(TextView.java:14423)
at android.widget.TextView.onTextContextMenuItem(TextView.java:13824)
at androidx.appcompat.widget.AppCompatEditText.onTextContextMenuItem(AppCompatEditText.java:11)
at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor..java:5347)
at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:5203)
at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:2)
at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:461)
at android.view.View.performClick(View.java:7792)
at android.view.View.performClickInternal(View.java:7769)
at android.view.View.access$3800(View.java:910)
at android.view.View$PerformClick.run(View.java:30218)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8751)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

User-Agent: "Tchap/2.4.2 (Linux; U; Android 12; SM-G996B Build/SP1A.210812.01; Flavour GooglePlay; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.2 [40204022] (G-dc462ebb-2022-08-29 15:54:43 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-G996B"

locale: "fr_FR"
matrix_sdk_version: "1.4.27 (dc462ebb)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "12 (API 31) G996BXXS5CVHI-REL"
server_version: "undefined"
theme: "system"
verbose_log: "OFF"

**Comment by Delphgateau** [comment]
+1 ici : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_c1225604-19ef-4a71-9af8-b86b4dd3c173/
