### ISSUE TITLE
Crash on open the "access by link" screen

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android#776]
crash call stack ---------------------------------
Element Build : 402050002
Element Version : 2.5.0 [402050002] (G-170dfd41-2022-11-10 09:56:55 +0100)
SDK Version : 1.4.36 (170dfd41)
Phone : Pixel 6a (9080065 13 REL)
Memory statuses
usedSize 130 MB
freeSize 16 MB
totalSize 147 MB
Thread: main, Exception: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.gouv.tchap.features.roomprofile.settings.linkaccess.TchapRoomLinkAccessFragment: could not find Fragment constructor
at androidx.fragment.app.Fragment.instantiate(Fragment.java:8)
at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:5)
at androidx.fragment.app.FragmentTransaction.createFragment(FragmentTransaction.java:3)
at im.vector.app.features.roomprofile.settings.RoomSettingsFragment.onAccessByLinkClicked(RoomSettingsFragment.kt:5)
at im.vector.app.features.roomprofile.settings.RoomSettingsController$buildModels$6.invoke(RoomSettingsController.kt:3)
at im.vector.app.features.roomprofile.settings.RoomSettingsController$buildModels$6.invoke(RoomSettingsController.kt:1)
at im.vector.app.core.epoxy.ListenerKt$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:1)
at im.vector.app.core.utils.DebouncedClickListener.onClick(DebouncedClickListener.kt:5)
at android.view.View.performClick(View.java:7506)
at android.view.View.performClickInternal(View.java:7483)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:29335)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NoSuchMethodException: fr.gouv.tchap.features.roomprofile.settings.linkaccess.TchapRoomLinkAccessFragment.<init> []
at java.lang.Class.getConstructor0(Class.java:2363)
at java.lang.Class.getConstructor(Class.java:1759)
at androidx.fragment.app.Fragment.instantiate(Fragment.java:4)
... 19 more

User-Agent: "Tchap/2.5.0 (Linux; U; Android 13; Pixel 6a Build/TP1A.221105.00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.36)"
Version: "2.5.0 [402050002] (G-170dfd41-2022-11-10 09:56:55 +0100)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "en_DE"
device: "Pixel 6a"
locale: "fr_FR"
matrix_sdk_version: "1.4.36 (170dfd41)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "13 (API 33) 9080065-REL"
server_version: "undefined"
theme: "system"

**Comment by jdauphant** [comment]
Same in 2.5.1

**Comment by giomfo** [comment]
fixed in v2.5.2
