### ISSUE TITLE
 Exception: NetworkConnection(ioException=java.io.IOException: Unexpected response code for CONNECT: 503)

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#789]
déconnexion non demandée et perte d'accès non prévue

crash call stack ---------------------------------
Element Build : 402040302
Element Version : 2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)
SDK Version : 1.4.27 (7466edf6)
Memory statuses
usedSize 211 MB
freeSize 2 MB
totalSize 214 MB
Thread: main, Exception: NetworkConnection(ioException=java.io.IOException: Unexpected response code for CONNECT: 503)
at org.matrix.android.sdk.internal.session.openid.DefaultGetOpenIdTokenTask.execute(GetOpenIdTokenTask.kt:32)
at org.matrix.android.sdk.internal.session.openid.DefaultGetOpenIdTokenTask$execute$1.invokeSuspend(Unknown Source:11)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7705)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@175ce8c, Dispatchers.Main.immediate]
Caused by: java.io.IOException: Unexpected response code for CONNECT: 503
at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:62)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:24)
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:20)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:30)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:37)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:36)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at org.matrix.android.sdk.internal.network.AccessTokenInterceptor.intercept(AccessTokenInterceptor.kt:31)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at org.matrix.android.sdk.internal.network.ApiInterceptor.intercept(ApiInterceptor.kt:7)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:57)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at org.matrix.android.sdk.internal.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:30)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at org.matrix.android.sdk.internal.network.TimeOutInterceptor.intercept(TimeOutInterceptor.kt:29)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:23)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:11)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

User-Agent: "Tchap/2.4.3-dev (Linux; U; Android 11;
Version: "2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)"
app_language: "fr_FR"
branch_name: "develop-ssi-neo"
can_contact: "false"
default_app_language: "fr_FR"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7466edf6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
server_version: "undefined"
theme: "system"
verbose_log: "OFF"

**Comment by Nivann** [comment]
"Je n'ai pas changé de réseau. Par contre j'ai eu quelques problèmes de déconnexion des VPN."

**Comment by Nivann** [comment]
+1  crash call stack ---------------------------------Element Build : 402040302
Element Version : 2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)
Memory statuses
usedSize 6 MB
freeSize 1 MB
totalSize 8 MB
Thread: main, Exception: NetworkConnection(ioException=java.net.UnknownHostException: Unable to resolve host "matrix.agent.pm.tchap.gouv.fr": No address associated with hostname)
at org.matrix.android.sdk.internal.session.openid.DefaultGetOpenIdTokenTask.execute(GetOpenIdTokenTask.kt:32)
at org.matrix.android.sdk.internal.session.openid.DefaultGetOpenIdTokenTask$execute$1.invokeSuspend(Unknown Source:11)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7721)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@727211b, Dispatchers.Main.immediate]
Caused by: java.net.UnknownHostException: Unable to resolve host "matrix.agent.pm.tchap.gouv.fr": No address associated with hostname
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
at java.net.InetAddress.getAllByName(InetAddress.java:1152)
at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:1)
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:64)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:20)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:30)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:37)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:36)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at org.matrix.android.sdk.internal.network.AccessTokenInterceptor.intercept(AccessTokenInterceptor.kt:31)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at org.matrix.android.sdk.internal.network.ApiInterceptor.intercept(ApiInterceptor.kt:7)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:57)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at org.matrix.android.sdk.internal.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:30)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at org.matrix.android.sdk.internal.network.TimeOutInterceptor.intercept(TimeOutInterceptor.kt:29)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:23)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:11)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
... 27 more

User-Agent: "Tchap/2.4.3-dev (Linux; U; Android 11; ; SAID 15af8f4fec423024; Flavour FDroid; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)"
app_language: "fr_FR"
branch_name: "develop-ssi-neo"
can_contact: "true"
default_app_language: "fr_FR"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7466edf6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "11 (API 30) 2022121510-REL"
server_version: "undefined"
theme: "system"
