### ISSUE TITLE
Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by AmelAlili** [tchapgouv/tchap-android#792]
tchap-android] [tchap] Toujours impossible de joindre un enregistrement sonore de quelques ko

User message:

[tchap] Toujours impossible de joindre un enregistrement sonore de quelques ko
 crash call stack ---------------------------------
Element Build : 402040402
Element Version : 2.4.4 [402040402] (G-7617c2c6-2022-10-12 16:14:18 +0200)
SDK Version : 1.4.27 (7617c2c6)
Phone : FIG-LX1 (9.1.0.216C432 9 REL)
Memory statuses
usedSize 13 MB
freeSize 1 MB
totalSize 15 MB
Thread: main, Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:534)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
... 1 more
Caused by: java.io.FileNotFoundException: Can't access /mnt/media_rw/C11D-10FC/Sounds/20221117_114038.amr
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1476)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1313)
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1166)
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1120)
at im.vector.lib.multipicker.utils.ContentResolverUtilKt.toMultiPickerAudioType(ContentResolverUtil.kt:9)
at im.vector.lib.multipicker.FilePicker.getSelectedFiles(FilePicker.kt:10)
at im.vector.app.features.attachments.AttachmentsHelper.onFileResult(AttachmentsHelper.kt:3)
at im.vector.app.features.home.room.detail.TimelineFragment$attachmentFileActivityResultLauncher$1.invoke(TimelineFragment.kt:4)
at im.vector.app.features.home.room.detail.TimelineFragment$attachmentFileActivityResultLauncher$1.invoke(TimelineFragment.kt:5)
at im.vector.app.core.extensions.FragmentKt$$ExternalSyntheticLambda0.onActivityResult(R8$$SyntheticClass:2)
at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:12)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
at androidx.fragment.app.Fragment.performStart(Fragment.java:7)
at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:3)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:11)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:8)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:22)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
at android.app.Activity.performStart(Activity.java:7479)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3454)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
... 3 more

User-Agent: "Tchap/2.4.4 (Linux; U; Android 9; FIG-LX1 Build/HUAWEIFIG-L3; Flavour GooglePlay; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.4 [402040402] (G-7617c2c6-2022-10-12 16:14:18 +0200)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "FIG-LX1"
device_id: "MDJEJUNSWO"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7617c2c6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "9 (API 28) 9.1.0.216C432-REL"
server_version: "undefined"
theme: "light"

**Comment by Delphgateau** [comment]
+1 : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_0f2fc335-cf53-4a9c-90fe-c44918d8e927/
