### ISSUE TITLE
Crypto_Thread, Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by AmelAlili** [tchapgouv/tchap-android#793]
tchap-android] [tchap] je ne peux plus ouvrir les fichiers pdf

User message:

[tchap] je ne peux plus ouvrir les fichiers pdf
 crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (F-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : Core-X4 NEO (2022031712 11 REL)
Memory statuses
usedSize 20 MB
freeSize 18 MB
totalSize 39 MB
Thread: Crypto_Thread, Exception: java.lang.NullPointerException
at org.matrix.android.sdk.internal.crypto.MXOlmDevice.addInboundGroupSession(MXOlmDevice.kt:5)
at org.matrix.android.sdk.internal.crypto.algorithms.megolm.MXMegolmDecryption.onRoomKeyEvent(MXMegolmDecryption.kt:77)
at org.matrix.android.sdk.internal.crypto.DefaultCryptoService$onToDeviceEvent$1.invokeSuspend(DefaultCryptoService.kt:176)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.4.3-dev (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID 6db0a61b42f7bb00; Flavour FDroid; MatrixAndroidSdk2 1.4.27)"
Version: "2.4.3-dev [402040302] (F-7466edf6-2022-09-23 16:18:08 +0200)"
app_language: "fr_FR"
branch_name: "develop-ssi-neo"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
device_id: "KLBTUQAUYK"
locale: "fr_FR"
matrix_sdk_version: "1.4.27 (7466edf6)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "11 (API 30) 2022121510-REL"
server_version: "undefined"
theme: "system"

**Comment by AmelAlili** [comment]
il a résolu le problème:

"Lorsque je voulais ouvrir le fichier il me marquait  aucune application externe n'a été trouvée pour effectuer cette action . J'ai enregistré le fichier que j'ai ouvert avec word et cela a fonctionné ."
