### ISSUE TITLE
Lors de la connexion l'application s'est arrêtée

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-android#829]
Ticket Crisp : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_fbfbf25a-df95-4df0-9634-36607ac36ac0/
"j'ai dû réinitialiser mon téléphone... je me connectais pour la première fois après réinitialisation , et lors de la connexion tout d'un coup l'application s'est arrêté"

Thread: main, Exception: java.lang.IllegalThreadStateException
at java.lang.Thread.start(Thread.java:960)
at org.matrix.android.sdk.internal.session.sync.DefaultSyncService.startSync(DefaultSyncService.kt:8)
at im.vector.app.R$id.startSyncing(Unknown Source:14)
at im.vector.app.core.di.ActiveSessionHolder.getOrInitializeSession(ActiveSessionHolder.kt:3)
at im.vector.app.core.di.ActiveSessionHolder$getSafeActiveSession$1.invokeSuspend(ActiveSessionHolder.kt:2)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:24)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:2)
at im.vector.app.core.di.ActiveSessionHolder.getSafeActiveSession$default(ActiveSessionHolder.kt:2)
at im.vector.app.features.home.HomeActivityViewModel.updateIdentityServer(HomeActivityViewModel.kt:1)
at im.vector.app.features.home.HomeActivityViewModel.access$updateIdentityServer(Unknown Source:0)
at im.vector.app.features.home.HomeActivityViewModel$observeInitialSync$1.invokeSuspend(HomeActivityViewModel.kt:3)
at im.vector.app.features.home.HomeActivityViewModel$observeInitialSync$1.invoke(Unknown Source:8)
at im.vector.app.features.home.HomeActivityViewModel$observeInitialSync$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:6)
at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:13)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:10)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:15)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:6)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:4)
at kotlinx.coroutines.flow.SharedFlowImpl.tryTakeValue(SharedFlow.kt:12)
at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:9)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8168)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ea0af8a, Dispatchers.Main.immediate]

User-Agent: "Tchap/2.5.2 (Xiaomi M2101K6G; Android 12;)
Version: "2.5.2 [402050202] (G-d616bb1b-2022-12-27 17:34:57 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
locale: "fr_FR"
matrix_sdk_version: "1.5.2 (d616bb1b)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "12 (API 31) V13.0.16.0.SKFEUXM-REL"
server_version: "undefined"
theme: "system"

**Comment by Delphgateau** [comment]
+1 : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_734ef716-81d2-4ddf-a344-ad8e4cf972e0/

Thread: main, Exception: java.lang.IllegalThreadStateException
at java.lang.Thread.start(Thread.java:872)
at org.matrix.android.sdk.internal.session.sync.DefaultSyncService.startSync(DefaultSyncService.kt:35)
at org.billcarsonfr.jsonviewer.R$id.startSyncing(Unknown Source:92)
at im.vector.app.core.di.ActiveSessionHolder.getOrInitializeSession(ActiveSessionHolder.kt:25)
at im.vector.app.core.di.ActiveSessionHolder$getSafeActiveSession$1.invokeSuspend(ActiveSessionHolder.kt:31)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:154)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:109)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:3)
at im.vector.app.core.di.ActiveSessionHolder.getSafeActiveSession(ActiveSessionHolder.kt:7)
at im.vector.app.features.home.HomeActivityViewModel.updateIdentityServer(HomeActivityViewModel.kt:4)
at im.vector.app.features.home.HomeActivityViewModel.access$updateIdentityServer(HomeActivityViewModel.kt:1)
at im.vector.app.features.home.HomeActivityViewModel$observeInitialSync$1.invokeSuspend(HomeActivityViewModel.kt:20)
at im.vector.app.features.home.HomeActivityViewModel$observeInitialSync$1.invoke(Unknown Source:8)
at im.vector.app.features.home.HomeActivityViewModel$observeInitialSync$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:74)
at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:200)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:52)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:105)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:44)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
at kotlinx.coroutines.flow.SharedFlowImpl.tryTakeValue(SharedFlow.kt:66)
at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:151)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:7864)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9980c04, Dispatchers.Main.immediate]
