### ISSUE TITLE
Exception: UID 10398 does not have permission to content

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-android#851]
Voir le ticket Crisp ici pour plus d'info : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_7191dd6e-27f6-42ec-b3e9-25463c503785/

Thread: main, Exception: java.lang.SecurityException: UID 10398 does not have permission to content://com.android.providers.media.documents/document/image%3A1000004610 [user 0]; you could obtain access using ACTION_OPEN_DOCUMENT or related APIs
at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
at android.os.Parcel.createException(Parcel.java:3007)
at android.os.Parcel.readException(Parcel.java:2990)
at android.os.Parcel.readException(Parcel.java:2932)
at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2774)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1801)
at android.app.Activity.startActivityForResult(Activity.java:5583)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
at android.app.Activity.startActivityForResult(Activity.java:5541)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
at android.app.Activity.startActivity(Activity.java:6039)
at android.app.Activity.startActivity(Activity.java:6006)
at im.vector.app.core.utils.ExternalApplicationsUtilKt.safeStartActivity(ExternalApplicationsUtil.kt:1)
at im.vector.app.features.home.room.detail.TimelineFragment.openFile(TimelineFragment.kt:4)
at im.vector.app.features.home.room.detail.TimelineFragment.startOpenFileIntent(TimelineFragment.kt:3)
at im.vector.app.features.home.room.detail.TimelineFragment.access$startOpenFileIntent(Unknown Source:0)
at im.vector.app.features.home.room.detail.TimelineFragment$onViewCreated$18.invoke(TimelineFragment.kt:14)
at im.vector.app.features.home.room.detail.TimelineFragment$onViewCreated$18.invoke(TimelineFragment.kt:1)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invokeSuspend(VectorBaseFragment.kt:3)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invoke(Unknown Source:8)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:6)
at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:13)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:10)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:15)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:6)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:4)
at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:6)
at im.vector.app.core.utils.PublishDataSource.post(Unknown Source:2)
at im.vector.app.features.home.room.detail.TimelineViewModel.handleOpenOrDownloadFile(TimelineViewModel.kt:9)
at im.vector.app.features.home.room.detail.TimelineViewModel.handle(TimelineViewModel.kt:14)
at im.vector.app.features.home.room.detail.TimelineFragment.onEventCellClicked(TimelineFragment.kt:5)
at im.vector.app.features.home.room.detail.timeline.helper.MessageItemAttributesFactory$create$2.invoke(MessageItemAttributesFactory.kt:4)
at im.vector.app.features.home.room.detail.timeline.helper.MessageItemAttributesFactory$create$2.invoke(MessageItemAttributesFactory.kt:1)
at im.vector.app.core.epoxy.ListenerKt$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:1)
at im.vector.app.core.utils.DebouncedClickListener.onClick(DebouncedClickListener.kt:5)
at android.view.View.performClick(View.java:7881)
at android.view.View.performClickInternal(View.java:7858)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30863)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8741)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@877a4d7, Dispatchers.Main.immediate]
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1306)
at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:643)
at com.android.server.uri.UriGrantsManagerService.-$$Nest$mcheckGrantUriPermissionFromIntentUnlocked(Unknown Source:0)
at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1496)
at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:700)

User-Agent: "Tchap/2.5.2

**Comment by yostyle** [comment]
duplicate of #642

**Comment by yostyle** [comment]
Duplicate #642

**Comment by Delphgateau** [comment]
+ 1 : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_19f64c43-59a4-4a5b-9ead-206670f8d40b/

**Comment by Delphgateau** [comment]
+1 : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_be25f829-e235-4943-b75d-46a7bfcfcc6f/
