### ISSUE TITLE
Exception: lateinit property avatarRenderer has not been initialized

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-android#861]
"je cherchais un correspondant et l'appli a planté" : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_ee1e1884-bcef-4844-bf0b-361913e291f9/

Thread: epoxy, Exception: kotlin.UninitializedPropertyAccessException: lateinit property avatarRenderer has not been initialized
at im.vector.app.features.userdirectory.InviteByEmailItem.getAvatarRenderer(InviteByEmailItem.kt:8)
at im.vector.app.features.userdirectory.InviteByEmailItem_.hashCode(InviteByEmailItem_.java:49)
at com.airbnb.epoxy.EpoxyModel.addWithDebugValidation(EpoxyModel.java:15)
at im.vector.app.features.userdirectory.InviteByEmailItem_.addTo(InviteByEmailItem_.java:4)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:1)
at im.vector.app.features.userdirectory.UserListController.buildModels(UserListController.kt:390)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:55)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.6.2 (Google Pixel 6 Pro; Android 13; TQ1A.230205.002; Flavour GooglePlay; MatrixAndroidSdk2 1.5.7)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "Pixel 6 Pro"
device_id: "LOIKUOROOW"
locale: "fr_FR"
matrix_sdk_version: "1.5.7 (120f8a53)"
multi_window: "OFF"

**Comment by Nivann** [comment]
possible similaire à : https://github.com/tchapgouv/tchap-android/issues/573

**Comment by Nivann** [comment]
+ 1 crash call stack ---------------------------------Element Build : 402060202
Element Version : 2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)
SDK Version : 1.5.7 (120f8a53)
Phone : Mi Note 10 Lite 
Memory statuses
usedSize 27 MB
freeSize 6 MB
totalSize 34 MB
Thread: epoxy, Exception: kotlin.UninitializedPropertyAccessException: lateinit property avatarRenderer has not been initialized
at im.vector.app.features.userdirectory.InviteByEmailItem.getAvatarRenderer(InviteByEmailItem.kt:8)
at im.vector.app.features.userdirectory.InviteByEmailItem_.hashCode(InviteByEmailItem_.java:49)
at com.airbnb.epoxy.EpoxyModel.addWithDebugValidation(EpoxyModel.java:15)
at im.vector.app.features.userdirectory.InviteByEmailItem_.addTo(InviteByEmailItem_.java:4)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:1)
at im.vector.app.features.userdirectory.UserListController.buildModels(UserListController.kt:390)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:55)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.6.2 (Xiaomi Mi Note 10 Lite; Android 11; RKQ1.200826.002 test-keys; Flavour GooglePlay; MatrixAndroidSdk2 1.5.7)"
Version: "2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "Mi Note 10 Lite"
locale: "fr_FR"
matrix_sdk_version: "1.5.7 (120f8a53)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "11 (API 30) V12.5.6.0.RFNEUXM-REL"
server_version: "undefined"
theme: "light"

**Comment by Delphgateau** [comment]
+1 : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_7a5d55ca-17a4-48a9-ad41-d65c69700b70/

**Comment by Delphgateau** [comment]
+ 1 : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_cbc3dd27-5474-488e-8650-eceb33ebe05f/
