### ISSUE TITLE
Thread: epoxy, Exception: kotlin.UninitializedPropertyAccess

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-android#864]
Crisp : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_67f7be0c-ae16-4a17-99bd-ab0ea32b1ff2/

Thread: epoxy, Exception: kotlin.UninitializedPropertyAccessException: lateinit property avatarRenderer has not been initialized
at im.vector.app.features.userdirectory.InviteByEmailItem.getAvatarRenderer(InviteByEmailItem.kt:8)
at im.vector.app.features.userdirectory.InviteByEmailItem_.hashCode(InviteByEmailItem_.java:49)
at com.airbnb.epoxy.EpoxyModel.addWithDebugValidation(EpoxyModel.java:15)
at im.vector.app.features.userdirectory.InviteByEmailItem_.addTo(InviteByEmailItem_.java:4)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:1)
at im.vector.app.features.userdirectory.UserListController.buildModels(UserListController.kt:390)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:55)
at android.os.Handler.handleCallback(Handler.java:869)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loop(Looper.java:206)
at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Nivann** [comment]
+1 

crash call stack ---------------------------------Element Build : 402060202
Element Version : 2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)
SDK Version : 1.5.7 (120f8a53)
Phone : 220333QNY 
Memory statuses
usedSize 38 MB
freeSize 6 MB
totalSize 45 MB
Thread: epoxy, Exception: kotlin.UninitializedPropertyAccessException: lateinit property avatarRenderer has not been initialized
at im.vector.app.features.userdirectory.InviteByEmailItem.getAvatarRenderer(InviteByEmailItem.kt:8)
at im.vector.app.features.userdirectory.InviteByEmailItem_.hashCode(InviteByEmailItem_.java:49)
at com.airbnb.epoxy.EpoxyModel.addWithDebugValidation(EpoxyModel.java:15)
at im.vector.app.features.userdirectory.InviteByEmailItem_.addTo(InviteByEmailItem_.java:4)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:1)
at im.vector.app.features.userdirectory.UserListController.buildModels(UserListController.kt:390)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:55)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:237)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.6.2 (Xiaomi 220333QNY; Android 11; RKQ1.211001.001 test-keys; Flavour GooglePlay; MatrixAndroidSdk2 1.5.7)"
Version: "2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "true"
default_app_language: "fr_FR"
device: "220333QNY"
locale: "fr_FR"
matrix_sdk_version: "1.5.7 (120f8a53)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "11 (API 30) V13.0.3.0.RGEEUXM-REL"
server_version: "undefined"
theme: "system"

**Comment by Nivann** [comment]
+ 1 

crash call stack ---------------------------------Element Build : 402060202
Element Version : 2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)
SDK Version : 1.5.7 (120f8a53)
Phone : STK-LX1
Memory statuses
usedSize 16 MB
freeSize 3 MB
totalSize 20 MB
Thread: epoxy, Exception: kotlin.UninitializedPropertyAccessException: lateinit property avatarRenderer has not been initialized
at im.vector.app.features.userdirectory.InviteByEmailItem.getAvatarRenderer(InviteByEmailItem.kt:8)
at im.vector.app.features.userdirectory.InviteByEmailItem_.hashCode(InviteByEmailItem_.java:49)
at com.airbnb.epoxy.EpoxyModel.addWithDebugValidation(EpoxyModel.java:15)
at im.vector.app.features.userdirectory.InviteByEmailItem_.addTo(InviteByEmailItem_.java:4)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:1)
at im.vector.app.features.userdirectory.UserListController.buildModels(UserListController.kt:390)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:55)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.6.2 (HUAWEI STK-LX1; Android 10; STK-L21 10.0.0.208(C431E8R1P2); Flavour GooglePlay; MatrixAndroidSdk2 1.5.7)"
Version: "2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "true"
default_app_language: "fr_FR"
device: "STK-LX1"
locale: "fr_FR"
matrix_sdk_version: "1.5.7 (120f8a53)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "10 (API 29) 10.0.0.208C431-REL"
server_version: "undefined"
theme: "system"

**Comment by Nivann** [comment]
+ 1 


crash call stack ---------------------------------Element Build : 402060202
Element Version : 2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)
SDK Version : 1.5.7 (120f8a53)
Phone : BV6600 
Memory statuses
usedSize 13 MB
freeSize 4 MB
totalSize 18 MB
Thread: epoxy, Exception: kotlin.UninitializedPropertyAccessException: lateinit property avatarRenderer has not been initialized
at im.vector.app.features.userdirectory.InviteByEmailItem.getAvatarRenderer(InviteByEmailItem.kt:8)
at im.vector.app.features.userdirectory.InviteByEmailItem_.hashCode(InviteByEmailItem_.java:49)
at com.airbnb.epoxy.EpoxyModel.addWithDebugValidation(EpoxyModel.java:15)
at im.vector.app.features.userdirectory.InviteByEmailItem_.addTo(InviteByEmailItem_.java:4)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:1)
at im.vector.app.features.userdirectory.UserListController.buildModels(UserListController.kt:390)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:55)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.6.2 (Blackview BV6600; Android 10; BV6600_EEA_ZN128F_V1.0_20220319V12; Flavour GooglePlay; MatrixAndroidSdk2 1.5.7)"
Version: "2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "BV6600"
locale: "fr_FR"
matrix_sdk_version: "1.5.7 (120f8a53)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "10 (API 29) 1647427150-REL"
server_version: "undefined"
theme: "system"

**Comment by jdauphant** [comment]
Duplica de https://github.com/tchapgouv/tchap-android/issues/864
