### ISSUE TITLE
Application crashes when naming room during creation

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-android#885]
On Tchap Android v2.7.2, when creating room, after typing the name of the room, if the user type the return key on the keyboard, the application crashes.

**Comment by NicolasBuquet** [comment]
Still present on Android Tchap v2.8.4

**Comment by yostyle** [comment]
@NicolasBuquet I can't reproduce it on Tchap android 2.9.3. Do you still have this issue on your device ?

**Comment by yostyle** [comment]
Crashlog Stacktrace :
```
Thread: main, Exception: java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
	at android.widget.TextView.onKeyUp(TextView.java:9670)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3688)
	at android.view.View.dispatchKeyEvent(View.java:14927)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:1004)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4225)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:1)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:11)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:19)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:23)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:3)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:22)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10400)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10248)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10204)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6539)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6403)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
