### ISSUE TITLE
Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#903]
crash sur l'écriture d'un message dans un salon.

crash call stack ---------------------------------Element Build : 402080002
Element Version : 2.8.0 [402080002] (G-c2011a29-2023-04-07 16:00:36 +0200)
SDK Version : 1.5.26 (c2011a29)
Phone : Pixel 6a 
Memory statuses
usedSize 384 MB
freeSize 0 MB
totalSize 385 MB
Thread: main, Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionEpoxyViewHolder{epoxyModel=AutocompleteEmojiItem_{emojiItem=EmojiItem(name=Green Circle, unicode=1F7E2, keywords=[circle, green, round, green-circle]), emojiTypeFace=android.graphics.Typeface@fd575b6b}AutocompleteEmojiItem_{id=7009531075258789032, viewType=2131493140, shown=true, addedToAdapter=false}, view=android.widget.LinearLayout{ad2d512 VFE...C.. [......ID](http://......id/) 0,1206-760,1340}, super=EpoxyViewHolder{13f3c9d position=8 id=7009531075258789032, oldPos=51, pLpos:0 no parent}} androidx.recyclerview.widget.RecyclerView{e65ce9b VFE...... [......ID](http://......id/) 0,0-760,1226}, adapter:com.airbnb.epoxy.EpoxyControllerAdapter@f21f195, layout:androidx.recyclerview.widget.LinearLayoutManager@d29d0b2, context:im.vector.app.VectorApplication@4207bd3
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:531)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:54)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:382)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:61)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:137)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:8)
at android.view.View.layout(View.java:23716)
at android.view.ViewGroup.layout(ViewGroup.java:6413)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23716)
at android.view.ViewGroup.layout(ViewGroup.java:6413)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23716)
at android.view.ViewGroup.layout(ViewGroup.java:6413)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4097)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3438)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2350)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9194)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:832)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

User-Agent: "Tchap/2.8.0 (Google Pixel 6a; Android 13; TQ2A.230305.008.E1; Flavour GooglePlay; MatrixAndroidSdk2 1.5.26)"
Version: "2.8.0 [402080002] (G-c2011a29-2023-04-07 16:00:36 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "en_DE"
device: "Pixel 6a"

locale: "fr_FR"
matrix_sdk_version: "1.5.26 (c2011a29)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "13 (API 33) 9677224-REL"
server_version: "undefined"
theme: "dark"

**Comment by yostyle** [comment]
Not reproduced on v2.9.3
