### ISSUE TITLE
Crash quand long message vocal

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-android#923]
Crisp : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_7568fbf1-c8e2-43da-aac6-71054023606f/

Thread: DefaultDispatcher-worker-13, Exception: java.lang.IllegalStateException
at android.media.AudioRecord.native_start(Native Method)
at android.media.AudioRecord.startRecording(AudioRecord.java:1042)
at im.vector.app.features.voice.VoiceRecorderL$startRecord$2.invokeSuspend(VoiceRecorderL.kt:20)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f4dd95d, Dispatchers.IO]

User-Agent: "Tchap/2.8.0 ; Flavour GooglePlay; MatrixAndroidSdk2 1.5.26)"
Version: "2.8.0 [402080002] (G-c2011a29-2023-04-07 16:00:36 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "HRY-LX1"
email: "undefined"
locale: "fr_FR"
matrix_sdk_version: "1.5.26 (c2011a29)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "9 (API 28) 289C431-REL"
server_version: "undefined"
theme: "system"

**Comment by NicolasBuquet** [comment]
Peut-être corrigé par Element :
- https://github.com/vector-im/element-android/pull/8382
- https://github.com/vector-im/element-android/pull/8313

A tester.

**Comment by yostyle** [comment]
@Delphgateau est ce que tu as toujours ce problème avec la version 2.11.0 de Tchap ?

**Comment by Delphgateau** [comment]
Non je viens de tester et ça marche jusqu'à 2mn et le message s'envoie sans problème.
