### ISSUE TITLE
Crash lors de l'accès aux réglages de sécurité (code pin ou biometrie)

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#930]
lors de la demande de gestion biométrie crash et retour à l accueil

crash call stack ---------------------------------Element Build : 402080402
Element Version : 2.8.4 [402080402] (G-82fea8db-2023-06-01 19:46:01 +0200)
SDK Version : 1.5.32 (82fea8db)
Phone : SM-F721B 
Memory statuses
usedSize 36 MB
freeSize 21 MB
totalSize 58 MB
Thread: main, Exception: java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner for VectorSettingsPinFragment{9f1fddf} (8033f8c2-3cc9-4ef4-af03-f3d92313611e id=0x7f0909ee) when getView() is null i.e., before onCreateView() or after onDestroyView()
at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:16)
at im.vector.app.features.settings.VectorSettingsPinFragment.refreshPinCodeStatus(VectorSettingsPinFragment.kt:1)
at im.vector.app.features.settings.VectorSettingsPinFragment.bindPref(VectorSettingsPinFragment.kt:1)
at im.vector.app.features.settings.VectorSettingsBaseFragment.onCreatePreferences(VectorSettingsBaseFragment.kt:8)
at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:74)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:22)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:51)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:149)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1137)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:82)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:74)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:4)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

User-Agent: "Tchap/2.8.4 (samsung SM-F721B; Android 13; TP1A.220624.014.F721BXXU2CWCC; Flavour GooglePlay; MatrixAndroidSdk2 1.5.32)"
Version: "2.8.4 [402080402] (G-82fea8db-2023-06-01 19:46:01 +0200)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-F721B"
locale: "fr_FR"
matrix_sdk_version: "1.5.32 (82fea8db)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "13 (API 33) F721BXXU2CWCC-REL"
server_version: "undefined"
theme: "system"

**Comment by NicolasBuquet** [comment]
C'est une version test (2.8.4) et cela semble concerner l'activation de la protection par code PIN.
Et en effet, comme tu l'as noté @Nivann, c'est la protection par Code PIN ou Biométrie.

On a déjà eu au moins une remontée au support sur du crash sur la biométrie il me semble.

**Comment by yostyle** [comment]
Fixed by https://github.com/tchapgouv/tchap-android/issues/936
